// frontend/src/components/tasks/TaskAttachments.vue
<template>
	<div class="space-y-2">
		<List v-if="rows.length" :columns="['auto', 'minmax(0,1fr)', 'auto']" divider="inset">
			<ListRow v-for="file in rows" :key="file.name" :value="file.name">
				<ListCell>
					<img
						v-if="isImage(file.file_name)"
						:src="file.file_url"
						:alt="file.file_name"
						class="size-8 rounded-2 object-cover"
					/>
					<span
						v-else
						:class="[fileIcon(file.file_name), 'size-4 text-ink-gray-5']"
						aria-hidden="true"
					/>
				</ListCell>
				<ListCell>
					<a
						:href="file.file_url"
						target="_blank"
						rel="noopener noreferrer"
						class="truncate text-base text-ink-gray-8 hover:underline"
					>
						{{ file.file_name }}
					</a>
				</ListCell>
				<ListCell>
					<div class="flex items-center gap-1.5">
						<Tooltip v-if="file.is_private" text="Private file">
							<span class="lucide-lock size-3.5 text-ink-gray-5" aria-hidden="true" />
						</Tooltip>
						<span class="text-sm tabular-nums text-ink-gray-5">
							{{ formatSize(file.file_size) }}
						</span>
						<Button
							variant="ghost"
							icon="lucide-download"
							:link="file.file_url"
							:download="file.file_name"
							aria-label="Download"
							tooltip="Download"
						/>
						<Button
							v-if="!readOnly"
							variant="ghost"
							theme="red"
							icon="lucide-trash-2"
							aria-label="Remove file"
							tooltip="Remove"
							:loading="files.delete.isLoading(file.name)"
							@click="remove(file)"
						/>
					</div>
				</ListCell>
			</ListRow>
		</List>

		<template v-if="!readOnly">
			<FileUploader
				:doctype="'Hive Task'"
				:docname="taskName"
				:private="isPrivate"
				:validate-file="validateFile"
				@success="onUploaded"
				@failure="onFailed"
			>
				<template #default="{ uploading, progress, openFileSelector }">
					<div
						class="flex cursor-pointer flex-col items-center justify-center gap-1.5 rounded-4 border border-dashed px-4 py-5 transition-colors"
						:class="
							dragOver
								? 'border-outline-gray-4 bg-surface-gray-2'
								: 'border-outline-gray-2 hover:border-outline-gray-3'
						"
						role="button"
						tabindex="0"
						@click="uploading || busy ? null : openFileSelector()"
						@keydown.enter.prevent="openFileSelector()"
						@keydown.space.prevent="openFileSelector()"
						@dragover.prevent="dragOver = true"
						@dragleave.prevent="dragOver = false"
						@drop.prevent="onDrop"
					>
						<template v-if="uploading || busy">
							<Spinner class="size-4 text-ink-gray-5" />
							<span class="text-sm text-ink-gray-5">
								{{ uploading ? `Uploading ${progress}%` : 'Uploading…' }}
							</span>
						</template>
						<template v-else>
							<span class="lucide-upload size-5 text-ink-gray-5" aria-hidden="true" />
							<span class="text-sm text-ink-gray-5">
								Drop files here or click to browse
							</span>
						</template>
					</div>
				</template>
			</FileUploader>

			<Switch
				v-model="isPrivate"
				size="sm"
				label="Upload as private"
				description="Private files are only visible to users with permission."
			/>
		</template>

		<p v-else-if="!rows.length" class="text-sm text-ink-gray-5">No attachments</p>
	</div>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import {
	Button,
	FileUploader,
	Spinner,
	Switch,
	Tooltip,
	dialog,
	toast,
	upload,
	useList,
} from 'frappe-ui'
import { List, ListCell, ListRow } from 'frappe-ui/list'
import type { Bool } from '@/types'

interface AttachedFile {
	name: string
	file_name: string
	file_url: string
	file_size: number
	is_private: Bool
}

const props = withDefaults(defineProps<{ taskName: string; readOnly?: boolean }>(), {
	readOnly: false,
})

/** Frappe's own default; anything larger is rejected before the request. */
const MAX_FILE_SIZE_MB = 10
const MAX_FILE_SIZE = MAX_FILE_SIZE_MB * 1024 * 1024

const isPrivate = ref(false)
const dragOver = ref(false)
/** Set while dropped files upload — `FileUploader` only tracks its own input. */
const busy = ref(false)

const files = useList<AttachedFile>({
	doctype: 'File',
	fields: ['name', 'file_name', 'file_url', 'file_size', 'is_private'],
	filters: () => ({
		attached_to_doctype: 'Hive Task',
		attached_to_name: props.taskName,
	}),
	orderBy: 'creation desc',
	limit: 50,
})

const rows = computed(() => files.data ?? [])

const IMAGE_EXTENSIONS = new Set(['png', 'jpg', 'jpeg', 'gif', 'svg', 'webp', 'avif'])

const EXTENSION_ICONS: Record<string, string> = {
	pdf: 'lucide-file-text',
	doc: 'lucide-file-text',
	docx: 'lucide-file-text',
	txt: 'lucide-file-text',
	md: 'lucide-file-text',
	xls: 'lucide-file-spreadsheet',
	xlsx: 'lucide-file-spreadsheet',
	csv: 'lucide-file-spreadsheet',
	mp4: 'lucide-file-video',
	mov: 'lucide-file-video',
	webm: 'lucide-file-video',
	avi: 'lucide-file-video',
	mp3: 'lucide-file-audio',
	wav: 'lucide-file-audio',
	flac: 'lucide-file-audio',
	ogg: 'lucide-file-audio',
	zip: 'lucide-file-archive',
	rar: 'lucide-file-archive',
	'7z': 'lucide-file-archive',
	gz: 'lucide-file-archive',
	tar: 'lucide-file-archive',
	js: 'lucide-file-code',
	ts: 'lucide-file-code',
	tsx: 'lucide-file-code',
	jsx: 'lucide-file-code',
	py: 'lucide-file-code',
	html: 'lucide-file-code',
	css: 'lucide-file-code',
	json: 'lucide-file-code',
	vue: 'lucide-file-code',
}

function extension(fileName: string): string {
	return fileName.split('.').pop()?.toLowerCase() ?? ''
}

function isImage(fileName: string): boolean {
	return IMAGE_EXTENSIONS.has(extension(fileName))
}

function fileIcon(fileName: string): string {
	return EXTENSION_ICONS[extension(fileName)] ?? 'lucide-file'
}

function formatSize(bytes: number): string {
	if (!bytes) return '0 B'
	if (bytes < 1024) return `${bytes} B`
	if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
	return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

function validateFile(file: File): string | null {
	if (file.size > MAX_FILE_SIZE) {
		return `"${file.name}" is larger than ${MAX_FILE_SIZE_MB}MB.`
	}
	return null
}

function onUploaded() {
	files.reload()
	toast.success('File uploaded')
}

function onFailed(error: unknown) {
	toast.error(error instanceof Error ? error.message : 'Failed to upload file')
}

/**
 * `FileUploader` owns a single hidden input, so a drag-and-drop of one or more
 * files goes straight through `upload()` with the same options.
 */
async function onDrop(event: DragEvent) {
	dragOver.value = false
	if (props.readOnly || busy.value) return
	const dropped = Array.from(event.dataTransfer?.files ?? [])
	if (!dropped.length) return

	const tooLarge = dropped.filter((file) => file.size > MAX_FILE_SIZE)
	if (tooLarge.length) {
		toast.error(`${tooLarge.length} file(s) exceed the ${MAX_FILE_SIZE_MB}MB limit.`)
		return
	}

	busy.value = true
	try {
		for (const file of dropped) {
			await upload(file, {
				private: isPrivate.value,
				doctype: 'Hive Task',
				docname: props.taskName,
			})
		}
		files.reload()
		toast.success(dropped.length === 1 ? 'File uploaded' : `${dropped.length} files uploaded`)
	} catch (error) {
		toast.error(error instanceof Error ? error.message : 'Failed to upload file')
	} finally {
		busy.value = false
	}
}

function remove(file: AttachedFile) {
	dialog.danger({
		title: 'Remove attachment?',
		message: `"${file.file_name}" will be deleted permanently.`,
		confirmLabel: 'Remove',
		onConfirm: async () => {
			try {
				await files.delete.submit({ name: file.name })
				files.reload()
				toast.success('File removed')
			} catch {
				toast.error('Failed to remove file')
			}
		},
	})
}
</script>

// frontend/src/components/TaskAttachments.tsx
import { useState, useRef, useCallback } from "react"
import { useFrappeFileUpload, useFrappeGetDocList, useFrappeDeleteDoc } from "frappe-react-sdk"
import { toast } from "sonner"
import { HugeiconsIcon } from "@hugeicons/react"
import {
  Upload04Icon,
  Cancel02Icon,
  File02Icon,
  Download04Icon,
  Pdf02Icon,
  Image02Icon,
  FileVideoIcon,
  FileAudioIcon,
  FileZipIcon,
  SourceCodeIcon,
  GoogleSheetIcon,
  DocumentAttachmentIcon,
  SquareLock02Icon,
} from "@hugeicons/core-free-icons"
import type { IconSvgElement } from "@hugeicons/react"
import { Spinner } from "@/components/ui/spinner"
import { cn } from "@/lib/utils"
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"
import { Label } from "@/components/ui/label"

interface FrappeFile {
  name: string
  file_name: string
  file_url: string
  file_size: number
  is_private: 0 | 1
}

function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

const EXT_ICON_MAP: Record<string, IconSvgElement> = {
  // Documents
  pdf: Pdf02Icon,
  // Images
  png: Image02Icon,
  jpg: Image02Icon,
  jpeg: Image02Icon,
  gif: Image02Icon,
  svg: Image02Icon,
  webp: Image02Icon,
  // Video
  mp4: FileVideoIcon,
  mov: FileVideoIcon,
  webm: FileVideoIcon,
  avi: FileVideoIcon,
  // Audio
  mp3: FileAudioIcon,
  wav: FileAudioIcon,
  flac: FileAudioIcon,
  ogg: FileAudioIcon,
  // Archives
  zip: FileZipIcon,
  rar: FileZipIcon,
  "7z": FileZipIcon,
  gz: FileZipIcon,
  tar: FileZipIcon,
  // Spreadsheets
  xls: GoogleSheetIcon,
  xlsx: GoogleSheetIcon,
  csv: GoogleSheetIcon,
  // Word docs
  doc: DocumentAttachmentIcon,
  docx: DocumentAttachmentIcon,
  // Code
  js: SourceCodeIcon,
  ts: SourceCodeIcon,
  tsx: SourceCodeIcon,
  jsx: SourceCodeIcon,
  py: SourceCodeIcon,
  html: SourceCodeIcon,
  css: SourceCodeIcon,
  json: SourceCodeIcon,
}

const IMAGE_EXTENSIONS = new Set(["png", "jpg", "jpeg", "gif", "svg", "webp"])

function isImageFile(fileName: string): boolean {
  const ext = fileName.split(".").pop()?.toLowerCase() ?? ""
  return IMAGE_EXTENSIONS.has(ext)
}

function getFileIcon(fileName: string): IconSvgElement {
  const ext = fileName.split(".").pop()?.toLowerCase() ?? ""
  return EXT_ICON_MAP[ext] ?? File02Icon
}

export function TaskAttachments({
  taskName,
  readOnly = false,
}: {
  taskName: string
  readOnly?: boolean
}) {
  const [uploading, setUploading] = useState(false)
  const [dragOver, setDragOver] = useState(false)
  const [pendingFiles, setPendingFiles] = useState<File[]>([])
  const [showUploadDialog, setShowUploadDialog] = useState(false)
  const [isPrivate, setIsPrivate] = useState(false)
  const fileInputRef = useRef<HTMLInputElement>(null)

  const { upload } = useFrappeFileUpload()
  const { deleteDoc } = useFrappeDeleteDoc()

  const { data: files, mutate } = useFrappeGetDocList<FrappeFile>("File", {
    fields: ["name", "file_name", "file_url", "file_size", "is_private"],
    filters: [
      ["attached_to_doctype", "=", "Hive Task"],
      ["attached_to_name", "=", taskName],
    ],
    orderBy: { field: "creation", order: "desc" },
    limit: 50,
  })

  const handleFilesSelected = useCallback(
    (fileList: FileList | File[]) => {
      const MAX_FILE_SIZE_MB = 10
      const MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * 1024 * 1024
      const filesToUpload = Array.from(fileList)
      if (filesToUpload.length === 0) return

      const oversized = filesToUpload.filter((f) => f.size > MAX_FILE_SIZE_BYTES)
      if (oversized.length > 0) {
        toast.error(
          oversized.length === 1
            ? `"${oversized[0].name}" is too large. Maximum size is ${MAX_FILE_SIZE_MB}MB.`
            : `${oversized.length} files exceed the ${MAX_FILE_SIZE_MB}MB limit.`,
        )
        return
      }

      setPendingFiles(filesToUpload)
      setIsPrivate(false)
      setShowUploadDialog(true)
    },
    [],
  )

  const confirmUpload = useCallback(async () => {
    if (pendingFiles.length === 0) return
    setShowUploadDialog(false)
    setUploading(true)
    try {
      for (const file of pendingFiles) {
        await upload(file, {
          isPrivate: isPrivate,
          doctype: "Hive Task",
          docname: taskName,
        })
      }
      await mutate()
      toast.success(
        pendingFiles.length === 1
          ? "File uploaded"
          : `${pendingFiles.length} files uploaded`,
      )
    } catch {
      toast.error("Failed to upload file")
    } finally {
      setUploading(false)
      setPendingFiles([])
      if (fileInputRef.current) fileInputRef.current.value = ""
    }
  }, [pendingFiles, isPrivate, taskName, upload, mutate])

  const handleRemove = async (file: FrappeFile) => {
    try {
      await deleteDoc("File", file.name)
      await mutate()
      toast.success("File removed")
    } catch {
      toast.error("Failed to remove file")
    }
  }

  const onDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault()
    setDragOver(true)
  }, [])

  const onDragLeave = useCallback((e: React.DragEvent) => {
    e.preventDefault()
    setDragOver(false)
  }, [])

  const onDrop = useCallback(
    (e: React.DragEvent) => {
      e.preventDefault()
      setDragOver(false)
      if (readOnly || uploading) return
      handleFilesSelected(e.dataTransfer.files)
    },
    [readOnly, uploading, handleFilesSelected],
  )

  return (
    <div className="grid gap-2">
      {/* File list */}
      {files && files.length > 0 && (
        <div className="space-y-1.5">
          {files.map((file) => (
            <div
              key={file.name}
              className="flex items-center gap-2 rounded-md border px-3 py-2 text-sm"
            >
              {isImageFile(file.file_name) ? (
                <img
                  src={file.file_url}
                  alt={file.file_name}
                  className="size-8 shrink-0 rounded object-cover"
                />
              ) : (
                <HugeiconsIcon
                  icon={getFileIcon(file.file_name)}
                  strokeWidth={2}
                  className="size-4 shrink-0 text-muted-foreground"
                />
              )}
              <a
                href={file.file_url}
                target="_blank"
                rel="noopener noreferrer"
                className="flex-1 truncate text-foreground hover:underline"
              >
                {file.file_name}
              </a>
              {file.is_private === 1 && (
                <HugeiconsIcon
                  icon={SquareLock02Icon}
                  strokeWidth={2}
                  className="size-3.5 shrink-0 text-muted-foreground"
                  title="Private file"
                />
              )}
              <span className="shrink-0 text-xs text-muted-foreground">
                {formatFileSize(file.file_size)}
              </span>
              <a
                href={file.file_url}
                download={file.file_name}
                className="shrink-0 text-muted-foreground hover:text-foreground"
              >
                <HugeiconsIcon icon={Download04Icon} strokeWidth={2} className="size-3.5" />
              </a>
              {!readOnly && (
                <button
                  type="button"
                  onClick={() => handleRemove(file)}
                  className="shrink-0 text-muted-foreground hover:text-destructive"
                >
                  <HugeiconsIcon icon={Cancel02Icon} strokeWidth={2} className="size-3.5" />
                </button>
              )}
            </div>
          ))}
        </div>
      )}

      {/* Drop zone */}
      {!readOnly && (
        <>
          <div
            onDragOver={onDragOver}
            onDragLeave={onDragLeave}
            onDrop={onDrop}
            onClick={() => !uploading && fileInputRef.current?.click()}
            className={cn(
              "flex cursor-pointer flex-col items-center justify-center gap-1.5 rounded-md border border-dashed px-4 py-5 transition-colors",
              dragOver
                ? "border-primary bg-primary/5"
                : "border-muted-foreground/25 hover:border-muted-foreground/50",
              uploading && "pointer-events-none opacity-60",
            )}
          >
            {uploading ? (
              <>
                <Spinner className="size-5" />
                <span className="text-xs text-muted-foreground">Uploading...</span>
              </>
            ) : (
              <>
                <HugeiconsIcon
                  icon={Upload04Icon}
                  strokeWidth={2}
                  className="size-5 text-muted-foreground"
                />
                <span className="text-xs text-muted-foreground">
                  Drop files here or click to browse
                </span>
              </>
            )}
          </div>
          <input
            ref={fileInputRef}
            type="file"
            multiple
            className="hidden"
            onChange={(e) => e.target.files && handleFilesSelected(e.target.files)}
          />
        </>
      )}
      {/* Upload confirmation dialog */}
      <Dialog
        open={showUploadDialog}
        onOpenChange={(open) => {
          if (!open) {
            setShowUploadDialog(false)
            setPendingFiles([])
            if (fileInputRef.current) fileInputRef.current.value = ""
          }
        }}
      >
        <DialogContent className="sm:max-w-sm">
          <DialogHeader>
            <DialogTitle>Upload files</DialogTitle>
            <DialogDescription>
              {pendingFiles.length === 1
                ? "1 file selected"
                : `${pendingFiles.length} files selected`}
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-3">
            <div className="max-h-32 space-y-1 overflow-y-auto">
              {pendingFiles.map((file, i) => (
                <div
                  key={i}
                  className="flex items-center gap-2 text-sm text-muted-foreground"
                >
                  <HugeiconsIcon
                    icon={getFileIcon(file.name)}
                    strokeWidth={2}
                    className="size-3.5 shrink-0"
                  />
                  <span className="truncate">{file.name}</span>
                  <span className="ml-auto shrink-0 text-xs">
                    {formatFileSize(file.size)}
                  </span>
                </div>
              ))}
            </div>
            <Label className="flex items-center gap-2 cursor-pointer">
              <Checkbox
                checked={isPrivate}
                onCheckedChange={(checked) => setIsPrivate(checked === true)}
              />
              <span>Upload as private</span>
            </Label>
            <p className="text-xs text-muted-foreground">
              Private files are only accessible to users with permission.
            </p>
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => {
                setShowUploadDialog(false)
                setPendingFiles([])
                if (fileInputRef.current) fileInputRef.current.value = ""
              }}
            >
              Cancel
            </Button>
            <Button onClick={confirmUpload}>Upload</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}
