// frontend/src/components/dashboard/MyWorkTab.vue
<template>
	<div class="space-y-6">
		<!-- KPI strip: one bordered box, the three readings divided inside it. -->
		<div
			class="grid grid-cols-1 divide-y divide-outline-gray-2 rounded-4 border border-outline-gray-1 bg-surface-base sm:grid-cols-3 sm:divide-x sm:divide-y-0"
		>
			<div
				v-for="kpi in kpis"
				:key="kpi.title"
				class="p-4"
				data-testid="kpi"
				:data-kpi="kpi.title"
			>
				<NumberCard
					:title="kpi.title"
					:value="kpi.value"
					:loading="loading"
					:error="errorMessage"
					:card="false"
				/>
			</div>
		</div>

		<!-- `items-start` so a short list does not stretch to match the tall one. -->
		<div class="grid items-start gap-6 lg:grid-cols-2">
			<DashboardSection title="My tasks" icon="lucide-list-checks">
				<div v-if="loading" class="space-y-2 p-2">
					<Skeleton v-for="n in 5" :key="n" class="h-8 w-full" />
				</div>
				<EmptyState
					v-else-if="!taskGroups.length"
					title="No open tasks"
					description="Tasks assigned to you show up here."
					icon="lucide-list-checks"
				/>
				<!-- Without explicit tracks and a row height, rows collapse to the
				     height of their text and the status dot claims a third of the
				     row. -->
				<List v-else :columns="TASK_COLUMNS" :row-height="36">
					<ListGroup v-for="group in taskGroups" :key="group.project">
						<template #header>
							<RouterLink
								:to="`/projects/${group.project}`"
								class="truncate hover:text-ink-gray-7"
							>
								{{ group.project_title }}
							</RouterLink>
						</template>
						<ListRow
							v-for="task in group.tasks"
							:key="task.name"
							:value="task.name"
							:to="taskRoute(task)"
						>
							<ListCell>
								<span
									:class="['size-2 rounded-full', statusDotClass(task.status)]"
									aria-hidden="true"
								/>
							</ListCell>
							<ListCell>
								<span class="truncate text-base text-ink-gray-8">{{
									task.title
								}}</span>
							</ListCell>
							<ListCell class="justify-end">
								<span
									v-if="task.due_date"
									:class="[
										'shrink-0 text-sm',
										isOverdue(task.due_date)
											? 'text-ink-red-6'
											: 'text-ink-gray-5',
									]"
								>
									{{ dueLabel(task.due_date) }}
								</span>
							</ListCell>
						</ListRow>
					</ListGroup>
				</List>
			</DashboardSection>

			<DashboardSection title="Recent updates" icon="lucide-megaphone">
				<template v-if="unreadCount" #actions>
					<Badge
						theme="blue"
						variant="subtle"
						size="sm"
						:label="`${unreadCount} unread`"
					/>
				</template>
				<div v-if="loading" class="space-y-2 p-2">
					<Skeleton v-for="n in 4" :key="n" class="h-12 w-full" />
				</div>
				<EmptyState
					v-else-if="!updates.length"
					title="No recent updates"
					description="Updates from your projects show up here."
					icon="lucide-megaphone"
				/>
				<!-- Two-line rows, so the height comes from the content; the tracks
				     still keep the unread dot and the timestamp off the text. -->
				<List v-else :columns="UPDATE_COLUMNS">
					<ListRow
						v-for="update in updates"
						:key="update.name"
						:value="update.name"
						:to="{ path: `/projects/${update.project}`, query: { tab: 'updates' } }"
					>
						<ListCell>
							<span
								v-if="update.is_unread"
								class="size-2 rounded-full bg-surface-blue-3"
								:aria-label="`Unread update in ${update.project_title}`"
							/>
							<span v-else class="size-2" aria-hidden="true" />
						</ListCell>
						<ListCell>
							<div class="min-w-0 py-2">
								<p
									class="flex items-center gap-1.5 truncate text-sm text-ink-gray-5"
								>
									<span
										:class="[
											'truncate',
											update.is_unread
												? 'font-semibold text-ink-gray-9'
												: 'font-medium text-ink-gray-8',
										]"
									>
										{{ update.posted_by_name }}
									</span>
									<span>in</span>
									<span class="truncate font-medium text-ink-gray-7">
										{{ update.project_title }}
									</span>
								</p>
								<p class="mt-1 line-clamp-2 text-p-sm text-ink-gray-6">
									{{ preview(update.content) }}
								</p>
							</div>
						</ListCell>
						<ListCell class="justify-end">
							<span class="shrink-0 text-sm text-ink-gray-5">
								{{ fromNow(update.creation) }}
							</span>
						</ListCell>
					</ListRow>
				</List>
			</DashboardSection>
		</div>

		<DashboardSection title="My projects" icon="lucide-folder" body-class="p-4">
			<div v-if="loading" class="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
				<Skeleton v-for="n in 3" :key="n" class="h-24 w-full rounded-4" />
			</div>
			<EmptyState
				v-else-if="!projects.length"
				title="No projects yet"
				description="Projects you are a member of show up here."
				icon="lucide-folder"
			/>
			<div v-else class="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
				<ProjectCard v-for="project in projects" :key="project.name" :project="project" />
			</div>
		</DashboardSection>
	</div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { RouterLink, type RouteLocationRaw } from 'vue-router'
import { Badge, Skeleton, useCall } from 'frappe-ui'
import { List, ListCell, ListGroup, ListRow } from 'frappe-ui/list'
import { NumberCard } from 'frappe-ui/charts'
import ProjectCard, { type ProjectCardProject } from '@/components/projects/ProjectCard.vue'
import DashboardSection from '@/components/dashboard/DashboardSection.vue'
import EmptyState from '@/components/common/EmptyState.vue'
import { dueLabel, fromNow, isOverdue } from '@/lib/dates'
import { statusDotClass } from '@/lib/status'
import { stripHtml, truncate } from '@/lib/text'
import type { Bool, TaskPriority, TaskStatus } from '@/types'

/** Shape of `bwh_hive.bwh_hive.api.get_my_dashboard`. */
interface DashboardTask {
	name: string
	title: string
	project: string
	status: TaskStatus
	priority: TaskPriority
	due_date: string | null
	is_internal: Bool
}

interface DashboardTaskGroup {
	project: string
	project_title: string
	project_status: string
	tasks: DashboardTask[]
}

interface DashboardUpdate {
	name: string
	project: string
	project_title: string
	posted_by: string
	posted_by_name: string
	content: string
	creation: string
	is_unread: boolean
}

interface MyDashboard {
	tasks_by_project: DashboardTaskGroup[]
	my_projects: ProjectCardProject[]
	unread_count: number
	recent_updates: DashboardUpdate[]
}

/** Status dot, title, then the due date pinned to the right. */
const TASK_COLUMNS = ['1rem', 'minmax(0, 1fr)', 'auto']

/** Unread dot, the update itself, then its age. */
const UPDATE_COLUMNS = ['1rem', 'minmax(0, 1fr)', 'auto']

/** Characters of stripped update text shown in the feed. */
const PREVIEW_LENGTH = 120

const dashboard = useCall<MyDashboard>({
	url: '/api/v2/method/bwh_hive.bwh_hive.api.get_my_dashboard',
	method: 'GET',
	cacheKey: 'my-dashboard',
})

const loading = computed(() => dashboard.loading && !dashboard.data)
const errorMessage = computed(() => (dashboard.error ? 'Could not load your dashboard.' : null))

const taskGroups = computed(() => dashboard.data?.tasks_by_project ?? [])
const projects = computed(() => dashboard.data?.my_projects ?? [])
const updates = computed(() => dashboard.data?.recent_updates ?? [])
const unreadCount = computed(() => dashboard.data?.unread_count ?? 0)

const openTasks = computed(() =>
	taskGroups.value.reduce((total, group) => total + group.tasks.length, 0),
)
const inProgressTasks = computed(() =>
	taskGroups.value.reduce(
		(total, group) =>
			total + group.tasks.filter((task) => task.status === 'In Progress').length,
		0,
	),
)

const kpis = computed(() => [
	{ title: 'Open tasks', value: openTasks.value },
	{ title: 'In progress', value: inProgressTasks.value },
	{ title: 'Unread updates', value: unreadCount.value },
])

function taskRoute(task: DashboardTask): RouteLocationRaw {
	return { path: `/projects/${task.project}`, query: { tab: 'tasks', task: task.name } }
}

function preview(content: string): string {
	return truncate(stripHtml(content), PREVIEW_LENGTH)
}
</script>

// frontend/src/components/dashboard/MyWorkTab.tsx
import { useFrappeGetCall } from "frappe-react-sdk"
import { Link } from "react-router"
import { HugeiconsIcon } from "@hugeicons/react"
import {
  TaskDaily01Icon,
  AlertCircleIcon,
  ArrowRight01Icon,
  Folder01Icon,
} from "@hugeicons/core-free-icons"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Skeleton } from "@/components/ui/skeleton"
import { PROJECT_STATUS_VARIANT, TASK_PRIORITY_COLOR } from "@/lib/variants"

interface MyDashboardData {
  tasks_by_project: {
    project: string
    project_title: string
    project_status: string
    tasks: {
      name: string
      title: string
      project: string
      status: string
      priority: string
      due_date: string | null
      is_internal: 0 | 1
    }[]
  }[]
  my_projects: {
    name: string
    title: string
    status: string
    project_type: string
    client: string
    modified: string
  }[]
  unread_count: number
  recent_updates: {
    name: string
    project: string
    project_title: string
    posted_by: string
    posted_by_name: string
    content: string
    creation: string
    is_unread: boolean
  }[]
}

export function MyWorkTab() {
  const { data, isLoading } = useFrappeGetCall<{ message: MyDashboardData }>(
    "bwh_hive.bwh_hive.api.get_my_dashboard",
  )

  if (isLoading) {
    return (
      <div className="space-y-6">
        <div className="grid gap-4 sm:grid-cols-3">
          {Array.from({ length: 3 }).map((_, i) => (
            <Card key={i}>
              <CardContent className="pt-6">
                <Skeleton className="h-8 w-16" />
                <Skeleton className="mt-2 h-4 w-24" />
              </CardContent>
            </Card>
          ))}
        </div>
        <div className="grid gap-4 lg:grid-cols-2">
          <Card>
            <CardHeader><Skeleton className="h-5 w-32" /></CardHeader>
            <CardContent><Skeleton className="h-32 w-full" /></CardContent>
          </Card>
          <Card>
            <CardHeader><Skeleton className="h-5 w-32" /></CardHeader>
            <CardContent><Skeleton className="h-32 w-full" /></CardContent>
          </Card>
        </div>
      </div>
    )
  }

  const dashboard = data?.message
  if (!dashboard) return null

  const totalTasks = dashboard.tasks_by_project.reduce(
    (sum, g) => sum + g.tasks.length, 0
  )
  const inProgressTasks = dashboard.tasks_by_project.reduce(
    (sum, g) => sum + g.tasks.filter((t) => t.status === "In Progress").length, 0
  )

  return (
    <div className="space-y-6">
      {/* Summary cards */}
      <div className="grid gap-4 sm:grid-cols-3">
        <Card>
          <CardContent className="pt-6">
            <p className="text-3xl font-bold">{totalTasks}</p>
            <p className="text-sm text-muted-foreground">Open tasks</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <p className="text-3xl font-bold">{inProgressTasks}</p>
            <p className="text-sm text-muted-foreground">In progress</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <p className="text-3xl font-bold">{dashboard.unread_count}</p>
            <p className="text-sm text-muted-foreground">Unread updates</p>
          </CardContent>
        </Card>
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        {/* My tasks grouped by project */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <HugeiconsIcon icon={TaskDaily01Icon} strokeWidth={2} className="size-5" />
              My Tasks
            </CardTitle>
          </CardHeader>
          <CardContent>
            {dashboard.tasks_by_project.length === 0 ? (
              <p className="text-sm text-muted-foreground">No open tasks assigned to you.</p>
            ) : (
              <div className="space-y-5">
                {dashboard.tasks_by_project.map((group) => (
                  <div key={group.project}>
                    <Link
                      to={`/projects/${group.project}`}
                      className="group mb-2 flex items-center gap-1.5 text-sm font-medium hover:underline"
                    >
                      {group.project_title}
                      <HugeiconsIcon
                        icon={ArrowRight01Icon}
                        strokeWidth={2}
                        className="size-3.5 opacity-0 transition-opacity group-hover:opacity-100"
                      />
                    </Link>
                    <ul className="space-y-1.5">
                      {group.tasks.map((task) => (
                        <li key={task.name} className="flex items-center gap-2 text-sm">
                          <span
                            className={`size-2 shrink-0 rounded-full ${
                              task.status === "In Progress"
                                ? "bg-blue-500"
                                : task.status === "Blocked"
                                  ? "bg-red-500"
                                  : task.status === "To Do"
                                    ? "bg-yellow-500"
                                    : "bg-muted-foreground/40"
                            }`}
                          />
                          <span className="truncate flex-1">{task.title}</span>
                          <span className={`text-xs shrink-0 ${TASK_PRIORITY_COLOR[task.priority] ?? ""}`}>
                            {task.priority}
                          </span>
                        </li>
                      ))}
                    </ul>
                  </div>
                ))}
              </div>
            )}
          </CardContent>
        </Card>

        {/* Recent updates */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <HugeiconsIcon icon={AlertCircleIcon} strokeWidth={2} className="size-5" />
              Recent Updates
              {dashboard.unread_count > 0 && (
                <Badge variant="default" className="ml-auto text-xs">
                  {dashboard.unread_count} unread
                </Badge>
              )}
            </CardTitle>
          </CardHeader>
          <CardContent>
            {dashboard.recent_updates.length === 0 ? (
              <p className="text-sm text-muted-foreground">No recent updates.</p>
            ) : (
              <ul className="space-y-3">
                {dashboard.recent_updates.map((upd) => (
                  <li key={upd.name} className="relative">
                    {upd.is_unread && (
                      <span className="absolute -left-3 top-1.5 size-1.5 rounded-full bg-blue-500" />
                    )}
                    <Link to={`/projects/${upd.project}?tab=updates`} className="block hover:bg-muted/50 rounded-md p-1 -m-1">
                      <div className="flex items-center gap-2 text-xs text-muted-foreground">
                        <span className="font-medium text-foreground">{upd.posted_by_name}</span>
                        <span>in</span>
                        <span className="font-medium">{upd.project_title}</span>
                        <span className="ml-auto">
                          {new Date(upd.creation).toLocaleDateString()}
                        </span>
                      </div>
                      <p
                        className="mt-0.5 text-sm line-clamp-2 text-muted-foreground"
                        dangerouslySetInnerHTML={{
                          __html: upd.content.replace(/<[^>]*>/g, " ").slice(0, 120),
                        }}
                      />
                    </Link>
                  </li>
                ))}
              </ul>
            )}
          </CardContent>
        </Card>
      </div>

      {/* My projects */}
      {dashboard.my_projects.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <HugeiconsIcon icon={Folder01Icon} strokeWidth={2} className="size-5" />
              My Projects
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
              {dashboard.my_projects.map((project) => (
                <Link
                  key={project.name}
                  to={`/projects/${project.name}`}
                  className="flex items-center gap-3 rounded-lg border p-3 transition-colors hover:bg-muted/50"
                >
                  <div className="min-w-0 flex-1">
                    <p className="text-sm font-medium truncate">{project.title}</p>
                    <div className="mt-1 flex items-center gap-1.5">
                      <Badge variant={PROJECT_STATUS_VARIANT[project.status] ?? "outline"} className="text-xs">
                        {project.status}
                      </Badge>
                      {project.project_type && (
                        <Badge variant="outline" className="text-xs">{project.project_type}</Badge>
                      )}
                    </div>
                  </div>
                  <HugeiconsIcon icon={ArrowRight01Icon} strokeWidth={2} className="size-4 shrink-0 text-muted-foreground" />
                </Link>
              ))}
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  )
}
