// frontend/src/components/dashboard/ProjectsTab.vue
<template>
	<div v-if="loading" class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
		<Skeleton v-for="n in 6" :key="n" class="h-32 w-full rounded-5" />
	</div>

	<ErrorMessage v-else-if="projects.error" :message="projects.error" />

	<EmptyState
		v-else-if="!projectList.length"
		title="No projects yet"
		description="Projects appear here once they are created."
		icon="lucide-folder"
	/>

	<div v-else class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
		<DashboardProjectCard v-for="project in projectList" :key="project.name" :project="project">
			<div
				class="mt-auto flex flex-wrap items-center gap-x-3 gap-y-1 text-sm text-ink-gray-5"
			>
				<span class="flex items-center gap-1">
					<span class="lucide-list-checks size-3.5" aria-hidden="true" />
					{{ counts(project.name).open }} open
				</span>
				<span v-if="counts(project.name).internal">
					{{ counts(project.name).internal }} internal
				</span>
				<span>{{ counts(project.name).total }} total</span>
			</div>
		</DashboardProjectCard>
	</div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { ErrorMessage, Skeleton, useList } from 'frappe-ui'
import DashboardProjectCard, {
	type DashboardProject,
} from '@/components/dashboard/DashboardProjectCard.vue'
import EmptyState from '@/components/common/EmptyState.vue'
import type { HiveProject, HiveTask } from '@/types'

/** Enough projects and tasks for an overview; the Projects page paginates. */
const PROJECT_LIMIT = 100
const TASK_LIMIT = 500

interface TaskCounts {
	total: number
	open: number
	/** Open tasks flagged internal — not visible to client members. */
	internal: number
}

const EMPTY_COUNTS: TaskCounts = { total: 0, open: 0, internal: 0 }

const projects = useList<HiveProject>({
	doctype: 'Hive Project',
	fields: ['name', 'title', 'slug', 'status', 'project_type', 'client', 'modified'],
	filters: { is_archived: 0 },
	orderBy: 'modified desc',
	limit: PROJECT_LIMIT,
	cacheKey: 'dashboard-projects',
})

const tasks = useList<HiveTask>({
	doctype: 'Hive Task',
	fields: ['name', 'project', 'status', 'is_internal'],
	filters: { is_archived: 0 },
	limit: TASK_LIMIT,
	cacheKey: 'dashboard-project-tasks',
})

const loading = computed(() => projects.loading && !projects.data)
const projectList = computed<DashboardProject[]>(() => projects.data ?? [])

const countsByProject = computed(() => {
	const map: Record<string, TaskCounts> = {}
	for (const task of tasks.data ?? []) {
		const entry = (map[task.project] ??= { total: 0, open: 0, internal: 0 })
		entry.total++
		if (task.status === 'Done') continue
		entry.open++
		if (task.is_internal) entry.internal++
	}
	return map
})

function counts(project: string): TaskCounts {
	return countsByProject.value[project] ?? EMPTY_COUNTS
}
</script>

// frontend/src/components/dashboard/ProjectsTab.tsx
import { useFrappeGetDocList } from "frappe-react-sdk"
import { Link } from "react-router"
import { HugeiconsIcon } from "@hugeicons/react"
import { Folder01Icon, TaskDaily01Icon } from "@hugeicons/core-free-icons"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Skeleton } from "@/components/ui/skeleton"
import { Empty, EmptyHeader, EmptyMedia, EmptyTitle, EmptyDescription } from "@/components/ui/empty"
import type { HiveProject, HiveTask } from "@/types"
import { PROJECT_STATUS_VARIANT } from "@/lib/variants"

export function ProjectsTab() {
  const { data: projects, isLoading: projectsLoading } = useFrappeGetDocList<HiveProject>(
    "Hive Project",
    {
      fields: ["name", "title", "status", "project_type", "client", "creation", "modified"],
      orderBy: { field: "modified", order: "desc" },
      limit: 100,
    },
  )

  const { data: tasks } = useFrappeGetDocList<HiveTask>(
    "Hive Task",
    {
      fields: ["name", "project", "status", "is_internal"],
      filters: [["is_archived", "=", 0]],
      limit: 500,
    },
  )

  if (projectsLoading) {
    return (
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {Array.from({ length: 3 }).map((_, i) => (
          <Card key={i}>
            <CardHeader>
              <Skeleton className="h-5 w-3/4" />
              <Skeleton className="h-4 w-1/2" />
            </CardHeader>
            <CardContent>
              <Skeleton className="h-4 w-full" />
            </CardContent>
          </Card>
        ))}
      </div>
    )
  }

  if (!projects?.length) {
    return (
      <Empty className="border rounded-2xl p-12">
        <EmptyHeader>
          <EmptyMedia>
            <HugeiconsIcon icon={Folder01Icon} strokeWidth={1.5} className="size-10 text-muted-foreground" />
          </EmptyMedia>
          <EmptyTitle>No projects yet</EmptyTitle>
          <EmptyDescription>Projects will appear here once created.</EmptyDescription>
        </EmptyHeader>
      </Empty>
    )
  }

  // Group tasks by project
  const tasksByProject: Record<string, { total: number; open: number; clientOpen: number }> = {}
  if (tasks) {
    for (const task of tasks) {
      if (!tasksByProject[task.project]) {
        tasksByProject[task.project] = { total: 0, open: 0, clientOpen: 0 }
      }
      tasksByProject[task.project].total++
      if (task.status !== "Done") {
        tasksByProject[task.project].open++
        if (task.is_internal) {
          tasksByProject[task.project].clientOpen++
        }
      }
    }
  }

  return (
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
      {projects.map((project) => {
        const stats = tasksByProject[project.name] ?? { total: 0, open: 0, clientOpen: 0 }
        return (
          <Link key={project.name} to={`/projects/${project.name}`} className="block">
            <Card className="h-full transition-shadow hover:shadow-md">
              <CardHeader>
                <CardTitle>{project.title}</CardTitle>
                <div className="flex flex-wrap items-center gap-1.5">
                  <Badge variant={PROJECT_STATUS_VARIANT[project.status] ?? "outline"}>
                    {project.status}
                  </Badge>
                  {project.project_type && (
                    <Badge variant="outline">{project.project_type}</Badge>
                  )}
                </div>
              </CardHeader>
              <CardContent>
                <div className="space-y-2">
                  {project.client && (
                    <p className="text-sm text-muted-foreground">{project.client}</p>
                  )}
                  <div className="flex items-center gap-3 text-xs text-muted-foreground">
                    <span className="flex items-center gap-1">
                      <HugeiconsIcon icon={TaskDaily01Icon} strokeWidth={2} className="size-3.5" />
                      {stats.open} open
                    </span>
                    {stats.clientOpen > 0 && (
                      <span>{stats.clientOpen} client</span>
                    )}
                    <span>{stats.total} total</span>
                  </div>
                </div>
              </CardContent>
            </Card>
          </Link>
        )
      })}
    </div>
  )
}
