// frontend/src/components/CreateProjectDialog.tsx
import { useState } from "react"
import { useFrappeCreateDoc } from "frappe-react-sdk"
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog"
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetDescription,
  SheetFooter,
} from "@/components/ui/sheet"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { LinkField } from "@/components/LinkField"
import { HugeiconsIcon } from "@hugeicons/react"
import { Add01Icon } from "@hugeicons/core-free-icons"
import { toast } from "sonner"

interface CreateProjectDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  onSubmit: (values: { title: string; project_type?: string; client?: string; is_private?: 0 | 1 }) => void
}

export function CreateProjectDialog({ open, onOpenChange, onSubmit }: CreateProjectDialogProps) {
  const [title, setTitle] = useState("")
  const [projectType, setProjectType] = useState("")
  const [client, setClient] = useState("")
  const [visibility, setVisibility] = useState<"Public" | "Private">("Public")
  const [newClientOpen, setNewClientOpen] = useState(false)
  const [newClientName, setNewClientName] = useState("")

  const { createDoc } = useFrappeCreateDoc()

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (!title.trim()) return
    onSubmit({
      title: title.trim(),
      ...(projectType && { project_type: projectType }),
      ...(client && { client }),
      is_private: visibility === "Private" ? 1 : 0,
    })
    setTitle("")
    setProjectType("")
    setClient("")
    setVisibility("Public")
  }

  const handleCreateClient = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!newClientName.trim()) return
    try {
      const doc = await createDoc("Hive Client", {
        company_name: newClientName.trim(),
      })
      toast.success("Client created")
      setClient(doc.name)
      setNewClientName("")
      setNewClientOpen(false)
    } catch {
      toast.error("Failed to create client")
    }
  }

  return (
    <>
      <Dialog open={open} onOpenChange={onOpenChange}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>New Project</DialogTitle>
            <DialogDescription>Create a new project.</DialogDescription>
          </DialogHeader>
          <form onSubmit={handleSubmit} className="grid gap-4">
            <div className="grid gap-2">
              <Label htmlFor="project-title">Title</Label>
              <Input
                id="project-title"
                placeholder="Project name"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                autoFocus
              />
            </div>

            <div className="grid gap-2">
              <Label>Visibility</Label>
              <Select value={visibility} onValueChange={(v) => setVisibility(v as "Public" | "Private")}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="Public">Public</SelectItem>
                  <SelectItem value="Private">Private</SelectItem>
                </SelectContent>
              </Select>
              {visibility === "Private" && (
                <p className="text-xs text-muted-foreground">
                  Only you will be able to see this project and its tasks.
                </p>
              )}
            </div>

            <div className="grid gap-2">
              <Label>Type</Label>
              <LinkField
                doctype="Hive Project Type"
                value={projectType}
                onChange={setProjectType}
                placeholder="Select type"
                filters={{ is_archived: 0 }}
                className="w-full justify-between"
              />
            </div>

            <div className="grid gap-2">
              <Label>Client</Label>
              <div className="flex items-center gap-2">
                <LinkField
                  doctype="Hive Client"
                  value={client}
                  onChange={setClient}
                  placeholder="Select client"
                  filters={{ is_active: 1 }}
                  className="w-full flex-1 justify-between"
                />
                <Button
                  type="button"
                  variant="outline"
                  size="icon"
                  onClick={() => setNewClientOpen(true)}
                >
                  <HugeiconsIcon icon={Add01Icon} strokeWidth={2} />
                </Button>
              </div>
            </div>

            <DialogFooter>
              <Button type="submit" disabled={!title.trim()}>
                Create Project
              </Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>

      <Sheet open={newClientOpen} onOpenChange={setNewClientOpen}>
        <SheetContent>
          <SheetHeader>
            <SheetTitle>New Client</SheetTitle>
            <SheetDescription>Add a new client to your workspace.</SheetDescription>
          </SheetHeader>
          <form onSubmit={handleCreateClient} className="grid gap-4 p-6">
            <div className="grid gap-2">
              <Label htmlFor="client-name">Company Name</Label>
              <Input
                id="client-name"
                placeholder="Acme Inc."
                value={newClientName}
                onChange={(e) => setNewClientName(e.target.value)}
                autoFocus
              />
            </div>
            <SheetFooter>
              <Button type="submit" disabled={!newClientName.trim()}>
                Create Client
              </Button>
            </SheetFooter>
          </form>
        </SheetContent>
      </Sheet>
    </>
  )
}

// frontend/src/components/projects/CreateProjectDialog.vue
<template>
	<Dialog :open="open" title="New Project" @update:open="emit('update:open', $event)">
		<template #default="{ close }">
			<form class="space-y-4" @submit.prevent="submit">
				<TextInput
					v-model="title"
					label="Title"
					placeholder="Project name"
					required
					autofocus
				/>

				<Select
					v-model="visibility"
					label="Visibility"
					:options="VISIBILITY_OPTIONS"
					:description="
						visibility === 'Private'
							? 'Only you will be able to see this project and its tasks.'
							: undefined
					"
				/>

				<LinkPicker
					v-model="projectType"
					doctype="Hive Project Type"
					label="Type"
					placeholder="Select type"
					:filters="{ is_archived: 0 }"
				/>

				<div class="flex items-end gap-2">
					<LinkPicker
						:key="clientPickerKey"
						v-model="client"
						class="min-w-0 flex-1"
						doctype="Hive Client"
						label="Client"
						placeholder="Select client"
						:filters="{ is_active: 1 }"
					/>
					<Button
						icon="lucide-plus"
						tooltip="New client"
						aria-label="New client"
						@click="newClientOpen = true"
					/>
				</div>

				<ErrorMessage :message="error" />

				<div class="flex justify-end gap-2 pt-2">
					<Button label="Cancel" @click="close" />
					<Button
						type="submit"
						variant="solid"
						theme="gray"
						label="Create Project"
						:loading="saving"
						:disabled="!title.trim()"
					/>
				</div>
			</form>
		</template>
	</Dialog>

	<NewClientDialog v-model:open="newClientOpen" @created="selectNewClient" />
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'
import { Button, Dialog, ErrorMessage, Select, TextInput, toast, useNewDoc } from 'frappe-ui'
import LinkPicker from '@/components/common/LinkPicker.vue'
import NewClientDialog from '@/components/projects/NewClientDialog.vue'
import type { HiveClient, HiveProject } from '@/types'

const props = defineProps<{ open: boolean }>()

const emit = defineEmits<{
	'update:open': [open: boolean]
	/** The inserted project, so the caller can navigate to it. */
	created: [project: HiveProject]
}>()

const VISIBILITY_OPTIONS = [
	{ label: 'Public', value: 'Public' },
	{ label: 'Private', value: 'Private' },
]

const title = ref('')
const visibility = ref('Public')
const projectType = ref<string | null>(null)
const client = ref<string | null>(null)
const newClientOpen = ref(false)
const saving = ref(false)
const error = ref('')

// A freshly created client is not in the picker's fetched page yet; remounting
// the picker re-runs its search so the selection has a label to render.
const clientPickerKey = ref(0)

watch(
	() => props.open,
	(open) => {
		if (open) return
		title.value = ''
		visibility.value = 'Public'
		projectType.value = null
		client.value = null
		error.value = ''
	},
)

function selectNewClient(created: HiveClient) {
	client.value = created.name
	clientPickerKey.value += 1
}

async function submit() {
	const projectTitle = title.value.trim()
	if (!projectTitle || saving.value) return

	saving.value = true
	error.value = ''
	try {
		const newDoc = useNewDoc<HiveProject>('Hive Project', {
			title: projectTitle,
			status: 'Open',
			is_private: visibility.value === 'Private' ? 1 : 0,
			...(projectType.value ? { project_type: projectType.value } : {}),
			...(client.value ? { client: client.value } : {}),
		})
		const created = await newDoc.submit()
		toast.success('Project created')
		emit('created', created)
		emit('update:open', false)
	} catch (e) {
		error.value = e instanceof Error ? e.message : 'Could not create project'
	} finally {
		saving.value = false
	}
}
</script>
