// frontend/src/components/project/ManageLinksDialog.tsx
import { useState, useRef } from "react"
import { HugeiconsIcon } from "@hugeicons/react"
import {
  Link04Icon,
  Delete02Icon,
  PencilEdit01Icon,
} from "@hugeicons/core-free-icons"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import type { HiveProjectLink } from "@/types"

interface ManageLinksDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  links: HiveProjectLink[]
  onAdd: (title: string, url: string) => void
  onRemove: (idx: number) => void
  onUpdate: (idx: number, title: string, url: string) => void
}

export function ManageLinksDialog({
  open,
  onOpenChange,
  links,
  onAdd,
  onRemove,
  onUpdate,
}: ManageLinksDialogProps) {
  const [newTitle, setNewTitle] = useState("")
  const [newUrl, setNewUrl] = useState("")
  const [editIdx, setEditIdx] = useState<number | null>(null)
  const [editTitle, setEditTitle] = useState("")
  const [editUrl, setEditUrl] = useState("")
  const titleRef = useRef<HTMLInputElement>(null)

  const handleAdd = () => {
    const title = newTitle.trim()
    const url = newUrl.trim()
    if (!title || !url) return
    onAdd(title, url)
    setNewTitle("")
    setNewUrl("")
    titleRef.current?.focus()
  }

  const startEdit = (idx: number) => {
    setEditIdx(idx)
    setEditTitle(links[idx].title)
    setEditUrl(links[idx].url)
  }

  const saveEdit = () => {
    if (editIdx === null) return
    const title = editTitle.trim()
    const url = editUrl.trim()
    if (!title || !url) return
    onUpdate(editIdx, title, url)
    setEditIdx(null)
  }

  const cancelEdit = () => setEditIdx(null)

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <DialogTitle>Related Links</DialogTitle>
        </DialogHeader>

        {/* Existing links */}
        {links.length > 0 && (
          <div className="space-y-2">
            {links.map((link, i) => (
              <div key={i}>
                {editIdx === i ? (
                  <div className="space-y-2 rounded-lg border p-3">
                    <Input
                      value={editTitle}
                      onChange={(e) => setEditTitle(e.target.value)}
                      placeholder="Title"
                    />
                    <Input
                      value={editUrl}
                      onChange={(e) => setEditUrl(e.target.value)}
                      placeholder="https://..."
                    />
                    <div className="flex gap-2">
                      <Button size="sm" onClick={saveEdit}>Save</Button>
                      <Button size="sm" variant="ghost" onClick={cancelEdit}>Cancel</Button>
                    </div>
                  </div>
                ) : (
                  <div className="flex items-center gap-2 rounded-lg border px-3 py-2 text-sm">
                    <HugeiconsIcon icon={Link04Icon} strokeWidth={2} className="size-4 text-muted-foreground shrink-0" />
                    <div className="flex-1 min-w-0">
                      <span className="font-medium">{link.title}</span>
                      <span className="text-muted-foreground ml-2 truncate text-xs">{link.url}</span>
                    </div>
                    <button
                      type="button"
                      onClick={() => startEdit(i)}
                      className="text-muted-foreground hover:text-foreground transition-colors"
                    >
                      <HugeiconsIcon icon={PencilEdit01Icon} strokeWidth={2} className="size-3.5" />
                    </button>
                    <button
                      type="button"
                      onClick={() => onRemove(i)}
                      className="text-muted-foreground hover:text-destructive transition-colors"
                    >
                      <HugeiconsIcon icon={Delete02Icon} strokeWidth={2} className="size-3.5" />
                    </button>
                  </div>
                )}
              </div>
            ))}
          </div>
        )}

        {/* Add new link */}
        <div className="space-y-2">
          <p className="text-xs text-muted-foreground font-medium">Add a link</p>
          <div className="flex gap-2">
            <Input
              ref={titleRef}
              value={newTitle}
              onChange={(e) => setNewTitle(e.target.value)}
              placeholder="Title"
              className="flex-1"
              onKeyDown={(e) => e.key === "Enter" && handleAdd()}
            />
            <Input
              value={newUrl}
              onChange={(e) => setNewUrl(e.target.value)}
              placeholder="https://..."
              className="flex-1"
              onKeyDown={(e) => e.key === "Enter" && handleAdd()}
            />
            <Button onClick={handleAdd} disabled={!newTitle.trim() || !newUrl.trim()}>
              Add
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}

// frontend/src/components/projects/ManageLinksDialog.vue
<template>
	<Dialog :open="open" title="Related links" @update:open="emit('update:open', $event)">
		<template #default>
			<div class="space-y-4">
				<div v-if="draft.length" class="space-y-2">
					<div
						v-for="(link, index) in draft"
						:key="index"
						class="flex items-center gap-2 rounded-3 border border-outline-gray-1 px-3 py-2"
					>
						<template v-if="editIndex === index">
							<TextInput
								v-model="editTitle"
								class="flex-1"
								placeholder="Title"
								aria-label="Link title"
							/>
							<TextInput
								v-model="editUrl"
								class="flex-1"
								placeholder="https://…"
								aria-label="Link URL"
							/>
							<Button
								variant="solid"
								theme="gray"
								label="Save"
								:disabled="!editTitle.trim() || !editUrl.trim()"
								@click="commitEdit"
							/>
							<Button label="Cancel" @click="editIndex = null" />
						</template>
						<template v-else>
							<span
								class="lucide-link size-4 shrink-0 text-ink-gray-5"
								aria-hidden="true"
							/>
							<span class="min-w-0 flex-1 truncate text-sm text-ink-gray-8">
								{{ link.title }}
								<span class="ml-2 text-xs text-ink-gray-5">{{ link.url }}</span>
							</span>
							<Button
								variant="ghost"
								icon="lucide-pencil"
								aria-label="Edit link"
								@click="startEdit(index)"
							/>
							<Button
								variant="ghost"
								icon="lucide-trash-2"
								aria-label="Remove link"
								@click="remove(index)"
							/>
						</template>
					</div>
				</div>

				<div class="space-y-2">
					<p class="text-sm font-medium text-ink-gray-6">Add a link</p>
					<div class="flex items-end gap-2">
						<TextInput
							v-model="newTitle"
							class="flex-1"
							placeholder="Title"
							aria-label="New link title"
							@keydown.enter.prevent="add"
						/>
						<TextInput
							v-model="newUrl"
							class="flex-1"
							placeholder="https://…"
							aria-label="New link URL"
							@keydown.enter.prevent="add"
						/>
						<Button
							variant="solid"
							theme="gray"
							label="Add"
							:disabled="!newTitle.trim() || !newUrl.trim()"
							@click="add"
						/>
					</div>
				</div>
			</div>
		</template>
	</Dialog>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'
import { Button, Dialog, TextInput } from 'frappe-ui'
import type { HiveProjectLink } from '@/types'

const props = defineProps<{
	open: boolean
	links: HiveProjectLink[]
}>()

const emit = defineEmits<{
	'update:open': [open: boolean]
	/** The whole child table, which is how Frappe wants it written back. */
	save: [links: HiveProjectLink[]]
}>()

// Edits apply straight away — the dialog is a live editor, not a form with an
// OK button, so every change goes out as a full child-table write.
const draft = ref<HiveProjectLink[]>([])

const newTitle = ref('')
const newUrl = ref('')
const editIndex = ref<number | null>(null)
const editTitle = ref('')
const editUrl = ref('')

watch(
	() => [props.open, props.links] as const,
	([open, links]) => {
		if (!open) return
		draft.value = links.map((link) => ({ ...link }))
		editIndex.value = null
	},
	{ immediate: true, deep: true },
)

function commit() {
	emit('save', draft.value)
}

function add() {
	const title = newTitle.value.trim()
	const url = newUrl.value.trim()
	if (!title || !url) return
	draft.value = [...draft.value, { title, url }]
	newTitle.value = ''
	newUrl.value = ''
	commit()
}

function remove(index: number) {
	draft.value = draft.value.filter((_, i) => i !== index)
	commit()
}

function startEdit(index: number) {
	editIndex.value = index
	editTitle.value = draft.value[index].title
	editUrl.value = draft.value[index].url
}

function commitEdit() {
	const index = editIndex.value
	if (index === null) return
	const title = editTitle.value.trim()
	const url = editUrl.value.trim()
	if (!title || !url) return
	draft.value = draft.value.map((link, i) => (i === index ? { ...link, title, url } : link))
	editIndex.value = null
	commit()
}
</script>
