// frontend/src/pages/ProjectsPage.tsx
import { useState, useMemo } from "react"
import { useFrappeGetDocList, useFrappeGetCall } from "frappe-react-sdk"
import { Link, useOutletContext } from "react-router"
import { HugeiconsIcon } from "@hugeicons/react"
import { Folder01Icon, Search01Icon, Add01Icon, LockIcon, UserIcon } from "@hugeicons/core-free-icons"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Input } from "@/components/ui/input"
import { Skeleton } from "@/components/ui/skeleton"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { PROJECT_STATUSES, type HiveProject } from "@/types"
import { PROJECT_STATUS_VARIANT } from "@/lib/variants"
import { useUser } from "@/context/UserContext"
import { Toggle } from "@/components/ui/toggle"
import {
  Empty,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle,
  EmptyDescription,
} from "@/components/ui/empty"

export function ProjectsPage() {
  const { openCreateProject } = useOutletContext<{ openCreateProject: () => void }>()
  const { isClient } = useUser()
  const [search, setSearch] = useState("")
  const [statusFilter, setStatusFilter] = useState(
    () => localStorage.getItem("hive_projects_status_filter") ?? "all"
  )
  const [scopeFilter, setScopeFilter] = useState(
    () => localStorage.getItem("hive_projects_scope_filter") ?? "All"
  )
  const [myProjectsOnly, setMyProjectsOnly] = useState(
    () => localStorage.getItem("hive_projects_my_only") === "true"
  )

  const handleStatusFilter = (value: string) => {
    setStatusFilter(value)
    localStorage.setItem("hive_projects_status_filter", value)
  }

  const handleScopeFilter = (value: string) => {
    setScopeFilter(value)
    localStorage.setItem("hive_projects_scope_filter", value)
  }

  const handleMyProjectsToggle = (pressed: boolean) => {
    setMyProjectsOnly(pressed)
    localStorage.setItem("hive_projects_my_only", String(pressed))
  }

  const { data: membershipData } = useFrappeGetCall<string[]>(
    "bwh_hive.bwh_hive.api.get_my_project_memberships",
  )

  const myProjectNames = useMemo(
    () => new Set(membershipData?.message ?? []),
    [membershipData],
  )

  const { data, isLoading } = useFrappeGetDocList<HiveProject>("Hive Project", {
    fields: ["name", "title", "slug", "status", "project_type", "client", "description", "is_private", "creation", "modified"],
    filters: [["is_archived", "=", 0]],
    orderBy: { field: "modified", order: "desc" },
    limit: 100,
  })

  const filteredProjects = useMemo(() => {
    if (!data) return []
    return data.filter((project) => {
      if (myProjectsOnly && !myProjectNames.has(project.name)) return false
      if (search) {
        const q = search.toLowerCase()
        const matchTitle = project.title.toLowerCase().includes(q)
        const matchClient = (project.client ?? "").toLowerCase().includes(q)
        const matchType = (project.project_type ?? "").toLowerCase().includes(q)
        if (!matchTitle && !matchClient && !matchType) return false
      }
      if (statusFilter !== "all" && project.status !== statusFilter) return false
      if (scopeFilter === "Internal" && project.client) return false
      if (scopeFilter === "External" && !project.client) return false
      return true
    })
  }, [data, search, statusFilter, scopeFilter, myProjectsOnly, myProjectNames])

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Projects</h1>
          <p className="mt-1 text-muted-foreground">Manage your projects.</p>
        </div>
        {!isClient && (
          <Button onClick={openCreateProject}>
            <HugeiconsIcon icon={Add01Icon} strokeWidth={2} className="size-4" />
            New Project
          </Button>
        )}
      </div>

      {/* Search & Filter */}
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center">
        <div className="relative flex-1 max-w-sm">
          <HugeiconsIcon
            icon={Search01Icon}
            strokeWidth={2}
            className="absolute left-2.5 top-1/2 -translate-y-1/2 size-4 text-muted-foreground"
          />
          <Input
            placeholder="Search projects..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="pl-8"
          />
        </div>
        <Select value={statusFilter} onValueChange={handleStatusFilter}>
          <SelectTrigger className="w-[140px]">
            <SelectValue placeholder="Status" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All statuses</SelectItem>
            {PROJECT_STATUSES.map((s) => (
              <SelectItem key={s} value={s}>{s}</SelectItem>
            ))}
          </SelectContent>
        </Select>
        <Select value={scopeFilter} onValueChange={handleScopeFilter}>
          <SelectTrigger className="w-[140px]">
            <SelectValue placeholder="Scope" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="All">All projects</SelectItem>
            <SelectItem value="Internal">Internal</SelectItem>
            <SelectItem value="External">External</SelectItem>
          </SelectContent>
        </Select>
        <Toggle
          pressed={myProjectsOnly}
          onPressedChange={handleMyProjectsToggle}
          variant="outline"
          size="sm"
          className="gap-1.5 aria-pressed:bg-primary aria-pressed:text-primary-foreground"
        >
          <HugeiconsIcon icon={UserIcon} strokeWidth={2} className="size-3.5" />
          My Projects
        </Toggle>
      </div>

      {isLoading ? (
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {Array.from({ length: 3 }).map((_, i) => (
            <Card key={i}>
              <CardHeader>
                <Skeleton className="h-5 w-3/4" />
                <Skeleton className="h-4 w-1/2" />
              </CardHeader>
              <CardContent>
                <Skeleton className="h-4 w-full" />
              </CardContent>
            </Card>
          ))}
        </div>
      ) : filteredProjects.length === 0 ? (
        <Empty className="border rounded-2xl p-12">
          <EmptyHeader>
            <EmptyMedia>
              <HugeiconsIcon icon={Folder01Icon} strokeWidth={1.5} className="size-10 text-muted-foreground" />
            </EmptyMedia>
            <EmptyTitle>
              {search || statusFilter !== "all" || scopeFilter !== "All" || myProjectsOnly ? "No projects match your filters" : "No projects yet"}
            </EmptyTitle>
            <EmptyDescription>
              {search || statusFilter !== "all" || scopeFilter !== "All" || myProjectsOnly
                ? "Try adjusting your search or filters."
                : "Projects will appear here once created."}
            </EmptyDescription>
          </EmptyHeader>
        </Empty>
      ) : (
        <>
          <p className="text-xs text-muted-foreground">
            {filteredProjects.length} project{filteredProjects.length !== 1 ? "s" : ""}
            {(search || statusFilter !== "all" || scopeFilter !== "All" || myProjectsOnly) && " matching filters"}
          </p>
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {filteredProjects.map((project) => (
              <Link key={project.name} to={`/projects/${project.slug || project.name}`} className="block">
                <Card className="h-full transition-shadow hover:shadow-md">
                  <CardHeader>
                    <CardTitle>{project.title}</CardTitle>
                    <CardDescription className="flex items-center gap-2">
                      <Badge variant={PROJECT_STATUS_VARIANT[project.status] ?? "outline"}>
                        {project.status}
                      </Badge>
                      {project.is_private === 1 && (
                        <Badge variant="outline" className="gap-1">
                          <HugeiconsIcon icon={LockIcon} strokeWidth={2} className="size-3" />
                          Private
                        </Badge>
                      )}
                      {project.project_type && (
                        <Badge variant="outline">{project.project_type}</Badge>
                      )}
                      {project.client && (
                        <Badge variant="outline">{project.client}</Badge>
                      )}
                    </CardDescription>
                  </CardHeader>
                  {project.description && (
                    <CardContent>
                      <p className="line-clamp-2 text-sm text-muted-foreground"
                         dangerouslySetInnerHTML={{ __html: project.description }}
                      />
                    </CardContent>
                  )}
                </Card>
              </Link>
            ))}
          </div>
        </>
      )}
    </div>
  )
}

// frontend/src/pages/ProjectsPage.vue
<template>
	<AppHeader title="Projects">
		<template #actions>
			<Button
				v-if="!isClient"
				variant="solid"
				theme="gray"
				icon-left="lucide-plus"
				label="New Project"
				@click="createProjectOpen = true"
			/>
		</template>
	</AppHeader>

	<div class="space-y-4 p-4 md:p-6">
		<div class="flex flex-col gap-3 sm:flex-row sm:items-center">
			<TextInput
				v-model="search"
				class="w-full sm:max-w-xs"
				placeholder="Search projects…"
				aria-label="Search projects"
			>
				<template #prefix>
					<span class="lucide-search size-4 text-ink-gray-5" aria-hidden="true" />
				</template>
			</TextInput>

			<Select
				v-model="statusFilter"
				class="sm:w-40"
				:options="STATUS_OPTIONS"
				aria-label="Filter by status"
			/>

			<Select
				v-model="scopeFilter"
				class="sm:w-40"
				:options="SCOPE_OPTIONS"
				aria-label="Filter by scope"
			/>

			<Switch v-model="myOnly" label="My projects" />
		</div>

		<div v-if="loading" class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
			<div
				v-for="n in 6"
				:key="n"
				class="space-y-3 rounded-4 border border-outline-gray-1 p-4"
			>
				<Skeleton class="h-5 w-3/4" />
				<Skeleton class="h-4 w-1/2" />
				<Skeleton class="h-4 w-full" />
			</div>
		</div>

		<ErrorMessage v-else-if="projects.error" :message="projects.error.message" />

		<EmptyState
			v-else-if="!filtered.length"
			icon="lucide-folder"
			:title="hasFilters ? 'No projects match your filters' : 'No projects yet'"
			:description="
				hasFilters
					? 'Try adjusting your search or filters.'
					: 'Projects will appear here once created.'
			"
		>
			<template v-if="!hasFilters && !isClient" #action>
				<Button
					variant="solid"
					theme="gray"
					icon-left="lucide-plus"
					label="New Project"
					@click="createProjectOpen = true"
				/>
			</template>
		</EmptyState>

		<template v-else>
			<p class="text-sm text-ink-gray-5">
				{{ filtered.length }} {{ filtered.length === 1 ? 'project' : 'projects' }}
				<span v-if="hasFilters">matching filters</span>
			</p>
			<div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
				<ProjectCard v-for="project in filtered" :key="project.name" :project="project" />
			</div>
		</template>
	</div>

	<CreateProjectDialog
		v-if="!isClient"
		v-model:open="createProjectOpen"
		@created="openCreatedProject"
	/>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import {
	Button,
	ErrorMessage,
	Select,
	Skeleton,
	Switch,
	TextInput,
	useCall,
	useList,
	usePageMeta,
} from 'frappe-ui'
import AppHeader from '@/components/shell/AppHeader.vue'
import EmptyState from '@/components/common/EmptyState.vue'
import CreateProjectDialog from '@/components/projects/CreateProjectDialog.vue'
import ProjectCard from '@/components/projects/ProjectCard.vue'
import { useOverlays } from '@/composables/useOverlays'
import { useSession } from '@/composables/useSession'
import { readStorage, STORAGE_KEYS, writeStorage } from '@/lib/storage'
import { PROJECT_STATUSES, type HiveProject } from '@/types'

usePageMeta(() => ({ title: 'Projects · Hive' }))

const ALL_STATUSES = 'all'
const ALL_SCOPES = 'All'

const STATUS_OPTIONS = [
	{ label: 'All statuses', value: ALL_STATUSES },
	...PROJECT_STATUSES.map((status) => ({ label: status, value: status })),
]

const SCOPE_OPTIONS = [
	{ label: 'All projects', value: ALL_SCOPES },
	{ label: 'Internal', value: 'Internal' },
	{ label: 'External', value: 'External' },
]

const router = useRouter()
const { isClient } = useSession()
const { createProjectOpen } = useOverlays()

const search = ref('')
const statusFilter = ref(readStorage(STORAGE_KEYS.projectsStatusFilter, ALL_STATUSES))
const scopeFilter = ref(readStorage(STORAGE_KEYS.projectsScopeFilter, ALL_SCOPES))
const myOnly = ref(readStorage(STORAGE_KEYS.projectsMyOnly, false))

watch(statusFilter, (value) => writeStorage(STORAGE_KEYS.projectsStatusFilter, value))
watch(scopeFilter, (value) => writeStorage(STORAGE_KEYS.projectsScopeFilter, value))
watch(myOnly, (value) => writeStorage(STORAGE_KEYS.projectsMyOnly, value))

const projects = useList<HiveProject>({
	doctype: 'Hive Project',
	fields: [
		'name',
		'title',
		'slug',
		'status',
		'project_type',
		'client',
		'description',
		'is_private',
		'creation',
		'modified',
	],
	filters: { is_archived: 0 },
	orderBy: 'modified desc',
	limit: 100,
	cacheKey: 'projects-list',
})

/** Project names the current user is a member of — drives the "My projects" switch. */
const memberships = useCall<string[]>({
	url: '/api/v2/method/bwh_hive.bwh_hive.api.get_my_project_memberships',
	method: 'GET',
	cacheKey: 'my-project-memberships',
})

const myProjectNames = computed(() => new Set(memberships.data ?? []))

// The memberships call only matters while "My projects" is on — without it the
// grid would flash an empty state before the names arrive.
const loading = computed(
	() =>
		(projects.loading && !projects.data) ||
		(myOnly.value && memberships.loading && !memberships.data),
)

const hasFilters = computed(
	() =>
		Boolean(search.value) ||
		statusFilter.value !== ALL_STATUSES ||
		scopeFilter.value !== ALL_SCOPES ||
		myOnly.value,
)

const filtered = computed(() => {
	const query = search.value.trim().toLowerCase()
	return (projects.data ?? []).filter((project) => {
		if (myOnly.value && !myProjectNames.value.has(project.name)) return false
		if (query) {
			const haystack = [project.title, project.client, project.project_type]
				.filter(Boolean)
				.join(' ')
				.toLowerCase()
			if (!haystack.includes(query)) return false
		}
		if (statusFilter.value !== ALL_STATUSES && project.status !== statusFilter.value)
			return false
		if (scopeFilter.value === 'Internal' && project.client) return false
		if (scopeFilter.value === 'External' && !project.client) return false
		return true
	})
})

function openCreatedProject(project: HiveProject) {
	projects.reload()
	router.push(`/projects/${project.slug || project.name}`)
}
</script>
