// frontend/src/components/projects/ActivityTab.vue
<template>
	<PageSkeleton v-if="activity.loading && !activity.data" :rows="5" />

	<EmptyState
		v-else-if="!items.length"
		icon="lucide-history"
		title="No activity yet"
		description="Changes to this project, its tasks and its milestones show up here."
	/>

	<div v-else class="space-y-2">
		<section v-for="day in days" :key="day.date">
			<button
				type="button"
				class="flex w-full items-center gap-2 py-2 text-left"
				:aria-expanded="!collapsed.has(day.date)"
				@click="toggle(day.date)"
			>
				<span
					class="lucide-chevron-down size-4 shrink-0 text-ink-gray-5 transition-transform"
					:class="{ '-rotate-90': collapsed.has(day.date) }"
					aria-hidden="true"
				/>
				<span class="text-sm font-medium text-ink-gray-8">{{ day.label }}</span>
				<Badge :label="String(day.items.length)" theme="gray" variant="subtle" />
			</button>

			<ol
				v-if="!collapsed.has(day.date)"
				class="ml-2 space-y-1 border-l border-outline-gray-1 pl-4"
			>
				<li
					v-for="(entry, index) in day.items"
					:key="`${entry.docname}-${index}`"
					class="py-1"
				>
					<div class="flex items-start gap-2">
						<MemberAvatar :name="entry.user_name" :image="entry.user_image" />
						<div class="min-w-0 flex-1">
							<p class="text-sm leading-snug text-ink-gray-7">
								<span class="font-medium text-ink-gray-8">{{
									entry.user_name
								}}</span>
								{{ ' ' }}{{ describe(entry) }}
								<span class="font-medium text-ink-gray-8">{{ entry.label }}</span>
								<span
									v-if="entry.old_value && entry.new_value"
									class="ml-1 inline-flex items-center gap-1 align-middle"
								>
									<Badge
										:label="truncate(entry.old_value, 30)"
										theme="gray"
										variant="outline"
									/>
									<span
										class="lucide-arrow-right size-3 text-ink-gray-5"
										aria-hidden="true"
									/>
									<Badge
										:label="truncate(entry.new_value, 30)"
										theme="gray"
										variant="outline"
									/>
								</span>
							</p>
							<p class="mt-0.5 text-xs text-ink-gray-5">
								{{ formatDate(entry.datetime, 'h:mm A') }}
							</p>
						</div>
					</div>
				</li>
			</ol>
		</section>
	</div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { Badge, useCall } from 'frappe-ui'
import EmptyState from '@/components/common/EmptyState.vue'
import MemberAvatar from '@/components/common/MemberAvatar.vue'
import PageSkeleton from '@/components/common/PageSkeleton.vue'
import { formatDate, groupByDay } from '@/lib/dates'
import { truncate } from '@/lib/text'

interface ActivityEntry {
	type: string
	doctype: string
	docname: string
	label: string
	field?: string
	old_value?: string
	new_value?: string
	user: string
	user_name: string
	user_image?: string | null
	datetime: string
}

const props = defineProps<{
	/** Hive Project docname. */
	project: string
}>()

const ACTIVITY_LIMIT = 100

/** Frappe field names read as jargon in a sentence; these are the readable ones. */
const FIELD_LABELS: Record<string, string> = {
	assigned_to: 'assignee',
	client: 'client',
	completed_on: 'completed date',
	description: 'description',
	due_date: 'due date',
	github_repo: 'GitHub repo',
	is_archived: 'archived flag',
	is_private: 'visibility',
	milestone: 'milestone',
	priority: 'priority',
	project_type: 'type',
	size: 'size',
	slug: 'URL slug',
	start_date: 'start date',
	status: 'status',
	target_date: 'target date',
	title: 'title',
	uat_status: 'UAT status',
}

const DOC_LABELS: Record<string, string> = {
	project_changed: 'project',
	task_changed: 'task',
	milestone_changed: 'milestone',
}

const activity = useCall<ActivityEntry[], { project: string; limit: number }>({
	url: '/api/v2/method/bwh_hive.bwh_hive.api.get_project_activity',
	method: 'POST',
	params: () => ({ project: props.project, limit: ACTIVITY_LIMIT }),
	immediate: false,
})

watch(
	() => props.project,
	(project) => project && activity.reload(),
	{ immediate: true },
)

const items = computed(() => activity.data ?? [])
const days = computed(() => groupByDay(items.value, (entry) => entry.datetime))

const collapsed = ref(new Set<string>())

function toggle(date: string) {
	const next = new Set(collapsed.value)
	if (!next.delete(date)) next.add(date)
	collapsed.value = next
}

/** The verb phrase before the document label, e.g. "changed status on task". */
function describe(entry: ActivityEntry): string {
	if (entry.type === 'task_created') return 'created task'
	if (entry.type === 'milestone_created') return 'created milestone'
	const field = FIELD_LABELS[entry.field ?? ''] ?? entry.field ?? 'a field'
	const doc = DOC_LABELS[entry.type] ?? 'record'
	return `changed ${field} on ${doc}`
}
</script>

// frontend/src/components/project/ActivityTab.tsx
import { useFrappePostCall } from "frappe-react-sdk"
import { useEffect, useMemo } from "react"
import { HugeiconsIcon } from "@hugeicons/react"
import {
  PencilEdit01Icon,
  Task01Icon,
  Target02Icon,
  Add01Icon,
  ArrowRight01Icon,
  ArrowDown01Icon,
} from "@hugeicons/core-free-icons"
import { Skeleton } from "@/components/ui/skeleton"
import { MemberAvatar } from "@/components/MemberAvatar"
import {
  Collapsible,
  CollapsibleTrigger,
  CollapsibleContent,
} from "@/components/ui/collapsible"
import { Badge } from "@/components/ui/badge"

interface ActivityItem {
  type: string
  doctype: string
  docname: string
  label: string
  field?: string
  old_value?: string
  new_value?: string
  user: string
  user_name: string
  user_image?: string | null
  datetime: string
}

// Group activities by date
function groupByDate(activities: ActivityItem[]): Map<string, ActivityItem[]> {
  const groups = new Map<string, ActivityItem[]>()
  for (const a of activities) {
    const date = a.datetime.split(" ")[0] // "2026-02-24"
    if (!groups.has(date)) groups.set(date, [])
    groups.get(date)!.push(a)
  }
  return groups
}

function formatDate(dateStr: string): string {
  const date = new Date(dateStr + "T00:00:00")
  const today = new Date()
  today.setHours(0, 0, 0, 0)
  const yesterday = new Date(today)
  yesterday.setDate(yesterday.getDate() - 1)

  if (date.getTime() === today.getTime()) return "Today"
  if (date.getTime() === yesterday.getTime()) return "Yesterday"

  return date.toLocaleDateString("en-US", {
    weekday: "short",
    month: "short",
    day: "numeric",
  })
}

function formatTime(datetimeStr: string): string {
  const date = new Date(datetimeStr.replace(" ", "T"))
  return date.toLocaleTimeString("en-US", {
    hour: "numeric",
    minute: "2-digit",
    hour12: true,
  })
}

const FIELD_LABELS: Record<string, string> = {
  status: "status",
  priority: "priority",
  title: "title",
  milestone: "milestone",
  assigned_to: "assignee",
  due_date: "due date",
  start_date: "start date",
  completed_on: "completed date",
  size: "size",
  uat_status: "UAT status",
  project_type: "type",
  client: "client",
  description: "description",
}

function getIcon(type: string) {
  switch (type) {
    case "project_changed":
      return PencilEdit01Icon
    case "task_created":
      return Add01Icon
    case "task_changed":
      return Task01Icon
    case "milestone_created":
      return Target02Icon
    case "milestone_changed":
      return Target02Icon
    default:
      return PencilEdit01Icon
  }
}

function getIconColor(type: string) {
  switch (type) {
    case "project_changed":
      return "text-blue-500"
    case "task_created":
      return "text-green-500"
    case "task_changed":
      return "text-amber-500"
    case "milestone_created":
      return "text-purple-500"
    case "milestone_changed":
      return "text-purple-500"
    default:
      return "text-muted-foreground"
  }
}

function ActivityDescription({ activity }: { activity: ActivityItem }) {
  const { type, label, field, old_value, new_value } = activity

  if (type === "task_created") {
    return (
      <span>
        created task <span className="font-medium">{label}</span>
      </span>
    )
  }

  if (type === "milestone_created") {
    return (
      <span>
        created milestone <span className="font-medium">{label}</span>
      </span>
    )
  }

  if (type === "task_changed" || type === "project_changed" || type === "milestone_changed") {
    const fieldLabel = FIELD_LABELS[field ?? ""] ?? field
    const docLabel = type === "project_changed" ? "project" : type === "milestone_changed" ? "milestone" : "task"

    return (
      <span>
        changed {fieldLabel} on {docLabel}{" "}
        <span className="font-medium">{label}</span>
        {old_value && new_value && (
          <span className="ml-1 inline-flex items-center gap-1 text-muted-foreground">
            <Badge variant="outline" className="text-[10px] h-4 px-1.5 font-normal">
              {String(old_value).substring(0, 30)}
            </Badge>
            <HugeiconsIcon icon={ArrowRight01Icon} className="size-3" strokeWidth={2} />
            <Badge variant="outline" className="text-[10px] h-4 px-1.5 font-normal">
              {String(new_value).substring(0, 30)}
            </Badge>
          </span>
        )}
      </span>
    )
  }

  return <span>{type}</span>
}

function ActivityEntry({ activity }: { activity: ActivityItem }) {
  const icon = getIcon(activity.type)
  const iconColor = getIconColor(activity.type)

  return (
    <div className="flex gap-3 py-2">
      <div className={`mt-0.5 flex-shrink-0 rounded-full bg-muted p-1.5 ${iconColor}`}>
        <HugeiconsIcon icon={icon} className="size-3.5" strokeWidth={2} />
      </div>
      <div className="flex-1 min-w-0">
        <div className="flex items-start gap-2 flex-wrap">
          <MemberAvatar name={activity.user_name} image={activity.user_image} size="sm" />
          <p className="text-sm leading-snug">
            <span className="font-medium">{activity.user_name}</span>{" "}
            <ActivityDescription activity={activity} />
          </p>
        </div>
        <p className="text-xs text-muted-foreground mt-0.5 ml-7">
          {formatTime(activity.datetime)}
        </p>
      </div>
    </div>
  )
}

function DateGroup({ date, activities }: { date: string; activities: ActivityItem[] }) {
  return (
    <Collapsible defaultOpen={true}>
      <CollapsibleTrigger className="flex items-center gap-2 w-full py-2 text-left group cursor-pointer">
        <HugeiconsIcon
          icon={ArrowDown01Icon}
          className="size-4 text-muted-foreground transition-transform group-data-[panel-open]:rotate-0 -rotate-90"
          strokeWidth={2}
        />
        <span className="text-sm font-medium">{formatDate(date)}</span>
        <Badge variant="outline" className="text-[10px] h-4 px-1.5">
          {activities.length}
        </Badge>
      </CollapsibleTrigger>
      <CollapsibleContent>
        <div className="ml-2 border-l border-border pl-4 space-y-0.5">
          {activities.map((activity, i) => (
            <ActivityEntry key={`${activity.docname}-${activity.datetime}-${i}`} activity={activity} />
          ))}
        </div>
      </CollapsibleContent>
    </Collapsible>
  )
}

export function ActivityTab({ projectId }: { projectId: string }) {
  const { call, result, loading } = useFrappePostCall(
    "bwh_hive.bwh_hive.api.get_project_activity",
  )

  useEffect(() => {
    call({ project: projectId, limit: 100 }).catch(() => {})
  }, [projectId, call])

  const activities = (result?.message ?? []) as ActivityItem[]

  const grouped = useMemo(() => groupByDate(activities), [activities])

  if (loading) {
    return (
      <div className="space-y-4 pt-4">
        {Array.from({ length: 3 }).map((_, i) => (
          <div key={i} className="space-y-2">
            <Skeleton className="h-5 w-24" />
            <Skeleton className="h-12 w-full" />
            <Skeleton className="h-12 w-full" />
          </div>
        ))}
      </div>
    )
  }

  if (activities.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-12 text-center">
        <p className="text-sm text-muted-foreground">No activity yet for this project.</p>
      </div>
    )
  }

  return (
    <div className="space-y-1 pt-2">
      {Array.from(grouped.entries()).map(([date, items]) => (
        <DateGroup key={date} date={date} activities={items} />
      ))}
    </div>
  )
}
