// frontend/src/components/projects/OverviewTab.vue
<template>
	<div class="space-y-6">
		<!-- KPI strip: one row of four, divided rather than boxed. -->
		<div
			class="grid grid-cols-2 divide-outline-gray-1 rounded-5 border border-outline-gray-1 sm:grid-cols-4 sm:divide-x"
		>
			<div v-for="stat in stats" :key="stat.label" class="px-4 py-3">
				<p class="text-sm text-ink-gray-5">{{ stat.label }}</p>
				<p
					class="mt-1 text-2xl font-semibold"
					:class="stat.alert ? 'text-ink-red-6' : 'text-ink-gray-9'"
				>
					{{ stat.value }}
				</p>
			</div>
		</div>

		<div class="grid gap-6 md:grid-cols-2">
			<section class="space-y-3">
				<h2 class="flex items-center gap-2 text-base font-medium text-ink-gray-8">
					<span class="lucide-target size-4 text-ink-gray-5" aria-hidden="true" />
					Active milestones
				</h2>

				<EmptyState
					v-if="!activeMilestones.length"
					icon="lucide-target"
					title="No active milestones"
					description="Create milestones to track project progress."
				/>

				<div v-else class="space-y-3">
					<div
						v-for="milestone in activeMilestones"
						:key="milestone.name"
						class="space-y-1.5"
					>
						<div class="flex items-center justify-between gap-2">
							<button
								type="button"
								class="flex min-w-0 items-center gap-1.5 text-sm text-ink-gray-8"
								:aria-expanded="expanded.has(milestone.name)"
								@click="toggle(milestone.name)"
							>
								<span
									class="lucide-chevron-down size-3 shrink-0 text-ink-gray-5 transition-transform"
									:class="{ '-rotate-90': !expanded.has(milestone.name) }"
									aria-hidden="true"
								/>
								<span class="truncate">{{ milestone.title }}</span>
							</button>
							<Badge
								:label="milestone.status"
								:theme="milestoneStatusTheme(milestone.status)"
								variant="subtle"
							/>
						</div>

						<template v-if="progress[milestone.name]?.tasks">
							<Progress :value="progress[milestone.name].percent" size="sm" />
							<div class="flex items-center justify-between text-xs text-ink-gray-5">
								<span>
									{{ progress[milestone.name].doneTasks }}/{{
										progress[milestone.name].tasks
									}}
									tasks
								</span>
								<span>{{ progress[milestone.name].percent }}%</span>
							</div>
						</template>
						<p v-else class="text-xs text-ink-gray-5">No tasks linked</p>

						<div
							v-if="expanded.has(milestone.name)"
							class="border-t border-outline-gray-1 pt-1.5"
						>
							<MilestoneTaskList
								:tasks="tasksByMilestone[milestone.name] ?? []"
								@select="emit('select-task', $event)"
							/>
						</div>
					</div>
				</div>
			</section>

			<section class="space-y-3">
				<div class="flex items-center justify-between gap-2">
					<h2 class="flex items-center gap-2 text-base font-medium text-ink-gray-8">
						<span class="lucide-users size-4 text-ink-gray-5" aria-hidden="true" />
						Team
					</h2>
					<MultiSelect
						v-if="!isClient"
						class="w-52"
						:model-value="memberIds"
						:options="memberOptions"
						placeholder="Add members"
						aria-label="Project members"
						@update:model-value="setMembers($event as (string | number)[])"
					/>
				</div>

				<EmptyState
					v-if="!members.length"
					icon="lucide-users"
					title="No team members"
					:description="
						isClient
							? 'Nobody has been added to this project yet.'
							: 'Add members with the picker above.'
					"
				/>

				<ul v-else class="space-y-2">
					<li
						v-for="member in members"
						:key="member.member"
						class="flex items-center gap-2 text-sm"
					>
						<MemberAvatar
							:name="member.member_name || member.member"
							:image="memberImages[member.member]"
						/>
						<span class="min-w-0 flex-1 truncate text-ink-gray-8">
							{{ member.member_name || member.member }}
						</span>
						<Badge
							v-if="isClient"
							:label="member.role"
							theme="gray"
							variant="outline"
						/>
						<template v-else>
							<Select
								class="w-32"
								:model-value="member.role"
								:options="ROLE_OPTIONS"
								size="sm"
								aria-label="Project role"
								@update:model-value="setRole(member.member, String($event))"
							/>
							<Button
								variant="ghost"
								size="sm"
								icon="lucide-x"
								aria-label="Remove member"
								@click="removeMember(member.member)"
							/>
						</template>
					</li>
				</ul>
			</section>
		</div>
	</div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import {
	Badge,
	Button,
	MultiSelect,
	Progress,
	Select,
	toast,
	useCall,
	useDoctype,
	useList,
} from 'frappe-ui'
import EmptyState from '@/components/common/EmptyState.vue'
import MemberAvatar from '@/components/common/MemberAvatar.vue'
import MilestoneTaskList from '@/components/projects/MilestoneTaskList.vue'
import { useSession } from '@/composables/useSession'
import { groupTasksByMilestone, milestoneProgress } from '@/lib/milestones'
import { milestoneStatusTheme } from '@/lib/status'
import type { HiveMember, HiveMilestone, HiveProject, HiveProjectMember, HiveTask } from '@/types'

const props = defineProps<{
	/** Hive Project docname. */
	project: string
	milestones: HiveMilestone[]
	tasks: HiveTask[]
}>()

const emit = defineEmits<{ 'select-task': [task: HiveTask] }>()

const ROLE_OPTIONS = ['Member', 'Champion', 'Stakeholder'].map((role) => ({
	label: role,
	value: role,
}))

const { isClient } = useSession()
const projectDoctype = useDoctype<HiveProject>('Hive Project')

// -- stats ---------------------------------------------------------------

const stats = computed(() => {
	let inProgress = 0
	let done = 0
	let blocked = 0
	for (const task of props.tasks) {
		if (task.status === 'In Progress') inProgress += 1
		else if (task.status === 'Done') done += 1
		else if (task.status === 'Blocked') blocked += 1
	}
	return [
		{ label: 'Total tasks', value: props.tasks.length, alert: false },
		{ label: 'In progress', value: inProgress, alert: false },
		{ label: 'Completed', value: done, alert: false },
		{ label: 'Blocked', value: blocked, alert: blocked > 0 },
	]
})

// -- milestones ----------------------------------------------------------

const tasksByMilestone = computed(() => groupTasksByMilestone(props.tasks))
const progress = computed(() => milestoneProgress(props.tasks))

/** The overview only carries what is still open, capped so it stays a summary. */
const ACTIVE_MILESTONE_LIMIT = 5
const activeMilestones = computed(() =>
	props.milestones.filter((m) => m.status !== 'Completed').slice(0, ACTIVE_MILESTONE_LIMIT),
)

const expanded = ref(new Set<string>())

function toggle(name: string) {
	const next = new Set(expanded.value)
	if (!next.delete(name)) next.add(name)
	expanded.value = next
}

// -- team ----------------------------------------------------------------

// The member rows come from the dashboard call because the child table stores
// only ids; the call resolves the names in one round trip.
const dashboard = useCall<{ members: HiveProjectMember[] }, { project: string }>({
	url: '/api/v2/method/bwh_hive.bwh_hive.api.get_project_dashboard',
	method: 'POST',
	params: () => ({ project: props.project }),
	immediate: false,
})

watch(
	() => props.project,
	() => props.project && dashboard.reload(),
	{ immediate: true },
)

const members = computed(() => dashboard.data?.members ?? [])
const memberIds = computed(() => members.value.map((m) => m.member))

const allMembers = useList<HiveMember>({
	doctype: 'Hive Member',
	fields: ['name', 'user', 'member_name', 'user_image', 'type', 'is_active'],
	filters: { is_active: 1 },
	orderBy: 'member_name asc',
	limit: 100,
	cacheKey: 'hive-active-members',
})

const memberOptions = computed(() =>
	(allMembers.data ?? []).map((member) => ({
		label: member.member_name || member.name,
		value: member.name,
	})),
)

const memberImages = computed(() =>
	Object.fromEntries((allMembers.data ?? []).map((m) => [m.name, m.user_image])),
)

async function saveMembers(rows: { member: string; role: string }[]) {
	try {
		// The child table only needs the link and the role; Frappe fetches the name.
		await projectDoctype.setValue.submit({
			name: props.project,
			members: rows as HiveProject['members'],
		})
		dashboard.reload()
	} catch {
		toast.error('Could not update the team')
	}
}

function setMembers(next: (string | number)[]) {
	const ids = next.map(String)
	const existing = new Map(members.value.map((m) => [m.member, m.role]))
	saveMembers(ids.map((id) => ({ member: id, role: existing.get(id) ?? 'Member' })))
}

function setRole(member: string, role: string) {
	saveMembers(
		members.value.map((m) => ({ member: m.member, role: m.member === member ? role : m.role })),
	)
}

function removeMember(member: string) {
	saveMembers(
		members.value
			.filter((m) => m.member !== member)
			.map((m) => ({ member: m.member, role: m.role })),
	)
}
</script>

// frontend/src/components/project/OverviewTab.tsx
import { useState, useEffect, useMemo } from "react"
import {
  useFrappeGetDocList,
  useFrappeUpdateDoc,
  useFrappePostCall,
} from "frappe-react-sdk"
import { format } from "date-fns"
import { HugeiconsIcon } from "@hugeicons/react"
import {
  Target02Icon,
  UserGroupIcon,
  UserAdd01Icon,
  CheckmarkCircle02Icon,
  Cancel02Icon,
  ArrowDown01Icon,
} from "@hugeicons/core-free-icons"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Progress } from "@/components/ui/progress"
import { MemberAvatar } from "@/components/MemberAvatar"
import {
  Collapsible,
  CollapsibleTrigger,
  CollapsibleContent,
} from "@/components/ui/collapsible"
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { toast } from "sonner"
import type { HiveProject, HiveMilestone, HiveMember, HiveTask } from "@/types"
import { TASK_SIZE_WEIGHT } from "@/types"
import { TASK_STATUS_COLOR } from "@/lib/variants"
import { useUser } from "@/context/UserContext"
import {
  Empty,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle,
  EmptyDescription,
} from "@/components/ui/empty"

interface OverviewTabProps {
  projectId: string
  project: HiveProject
  stats: {
    totalTasks: number
    inProgressTasks: number
    doneTasks: number
    blockedTasks: number
  }
  milestones: HiveMilestone[] | undefined
  tasks?: HiveTask[]
  onTaskClick?: (task: HiveTask) => void
}

function getWeight(size: string | null | undefined): number {
  return TASK_SIZE_WEIGHT[size ?? ""] ?? 1
}

function sortTasksByDueDate(tasks: HiveTask[]): HiveTask[] {
  return [...tasks].sort((a, b) => {
    if (a.due_date && b.due_date) return a.due_date.localeCompare(b.due_date)
    if (a.due_date && !b.due_date) return -1
    if (!a.due_date && b.due_date) return 1
    return 0
  })
}

export function OverviewTab({ projectId, project, stats, milestones, tasks, onTaskClick }: OverviewTabProps) {
  const { isClient } = useUser()
  const { updateDoc } = useFrappeUpdateDoc()
  const [expandedMilestones, setExpandedMilestones] = useState<Set<string>>(new Set())

  const toggleExpanded = (name: string) => {
    setExpandedMilestones((prev) => {
      const next = new Set(prev)
      if (next.has(name)) next.delete(name)
      else next.add(name)
      return next
    })
  }

  // Group tasks by milestone, sorted by due date
  const tasksByMilestone = useMemo(() => {
    const map: Record<string, HiveTask[]> = {}
    if (!tasks) return map
    for (const task of tasks) {
      if (!task.milestone) continue
      if (!map[task.milestone]) map[task.milestone] = []
      map[task.milestone].push(task)
    }
    for (const key of Object.keys(map)) {
      map[key] = sortTasksByDueDate(map[key])
    }
    return map
  }, [tasks])
  const { call: callDashboard, result: dashboardResult } = useFrappePostCall(
    "bwh_hive.bwh_hive.api.get_project_dashboard",
  )

  const { data: allMembers } = useFrappeGetDocList<HiveMember>(
    "Hive Member",
    {
      fields: ["name", "user", "member_name", "user_image", "type", "is_active"],
      filters: [["is_active", "=", 1]],
      limit: 100,
    },
  )

  const allMembersByName = useMemo(() => {
    const map = new Map<string, HiveMember>()
    if (allMembers) {
      for (const m of allMembers) {
        map.set(m.name, m)
      }
    }
    return map
  }, [allMembers])

  const [teamMembers, setTeamMembers] = useState<
    { member: string; member_name: string; role: string }[]
  >([])

  useEffect(() => {
    callDashboard({ project: projectId }).catch(() => {})
  }, [projectId, callDashboard])

  useEffect(() => {
    const members = (
      dashboardResult?.message as {
        members?: { member: string; member_name: string; role: string }[]
      }
    )?.members
    if (members) {
      setTeamMembers(members)
    }
  }, [dashboardResult])

  const teamMemberSet = useMemo(
    () => new Set(teamMembers.map((m) => m.member)),
    [teamMembers],
  )

  const saveProjectMembers = async (
    members: { member: string; member_name: string; role: string }[],
  ) => {
    try {
      await updateDoc("Hive Project", projectId, {
        members: members.map((m) => ({ member: m.member, role: m.role })),
      })
      callDashboard({ project: projectId }).catch(() => {})
    } catch {
      toast.error("Failed to update team")
    }
  }

  const toggleTeamMember = (member: HiveMember) => {
    const exists = teamMemberSet.has(member.name)
    const next = exists
      ? teamMembers.filter((m) => m.member !== member.name)
      : [
          ...teamMembers,
          { member: member.name, member_name: member.member_name, role: "Member" },
        ]
    setTeamMembers(next)
    saveProjectMembers(next)
  }

  const changeTeamMemberRole = (memberName: string, role: string) => {
    const next = teamMembers.map((m) =>
      m.member === memberName ? { ...m, role } : m,
    )
    setTeamMembers(next)
    saveProjectMembers(next)
  }

  const removeTeamMember = (memberName: string) => {
    const next = teamMembers.filter((m) => m.member !== memberName)
    setTeamMembers(next)
    saveProjectMembers(next)
  }

  // Compute weighted progress per milestone
  const progressByMilestone = useMemo(() => {
    const map: Record<string, { total: number; done: number; taskCount: number; doneCount: number }> = {}
    if (!tasks) return map
    for (const task of tasks) {
      if (!task.milestone) continue
      if (!map[task.milestone]) {
        map[task.milestone] = { total: 0, done: 0, taskCount: 0, doneCount: 0 }
      }
      const w = getWeight(task.size)
      map[task.milestone].total += w
      map[task.milestone].taskCount += 1
      if (task.status === "Done") {
        map[task.milestone].done += w
        map[task.milestone].doneCount += 1
      }
    }
    return map
  }, [tasks])

  const { totalTasks, inProgressTasks, doneTasks, blockedTasks } = stats
  const activeMilestones = milestones?.filter((m) => m.status === "In Progress").length ?? 0

  return (
    <div className="space-y-6 pt-2">
      {/* Stats Cards */}
      <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
        <StatCard label="Total Tasks" value={totalTasks} />
        <StatCard label="In Progress" value={inProgressTasks} />
        <StatCard label="Completed" value={doneTasks} />
        <StatCard label="Blocked" value={blockedTasks} variant={blockedTasks > 0 ? "destructive" : undefined} />
      </div>

      {/* Active Milestones & Team */}
      <div className="grid gap-6 md:grid-cols-2">
        {/* Active Milestones */}
        <Card>
          <CardHeader>
            <CardTitle className="text-sm font-medium flex items-center gap-2">
              <HugeiconsIcon icon={Target02Icon} strokeWidth={2} className="size-4" />
              Active Milestones
            </CardTitle>
          </CardHeader>
          <CardContent>
            {activeMilestones > 0 ? (
              <div className="space-y-3">
                {milestones
                  ?.filter((m) => m.status !== "Completed")
                  .slice(0, 5)
                  .map((ms) => {
                    const progress = progressByMilestone[ms.name]
                    const pct = progress && progress.total > 0
                      ? Math.round((progress.done / progress.total) * 100)
                      : 0
                    const milestoneTasks = tasksByMilestone[ms.name] ?? []
                    const isExpanded = expandedMilestones.has(ms.name)
                    return (
                      <Collapsible key={ms.name} open={isExpanded} onOpenChange={() => toggleExpanded(ms.name)}>
                        <div className="space-y-1.5">
                          <div className="flex items-center justify-between text-sm">
                            <CollapsibleTrigger
                              render={
                                <button type="button" className="flex items-center gap-1.5 hover:text-foreground transition-colors" />
                              }
                            >
                              <HugeiconsIcon
                                icon={ArrowDown01Icon}
                                strokeWidth={2}
                                className={`size-3 text-muted-foreground transition-transform ${isExpanded ? "" : "-rotate-90"}`}
                              />
                              <span>{ms.title}</span>
                            </CollapsibleTrigger>
                            <Badge
                              variant={ms.status === "In Progress" ? "secondary" : "outline"}
                              className="text-[10px] h-4 px-1.5"
                            >
                              {ms.status}
                            </Badge>
                          </div>
                          {progress && progress.total > 0 ? (
                            <div className="space-y-1">
                              <Progress value={pct} className="h-1.5" />
                              <div className="flex items-center justify-between text-[10px] text-muted-foreground">
                                <span>{progress.doneCount}/{progress.taskCount} tasks</span>
                                <span>{pct}%</span>
                              </div>
                            </div>
                          ) : (
                            <p className="text-[10px] text-muted-foreground">No tasks linked</p>
                          )}
                        </div>
                        <CollapsibleContent>
                          <div className="mt-1.5 border-t pt-1.5">
                            {milestoneTasks.length === 0 ? (
                              <p className="text-[11px] text-muted-foreground py-1">No tasks in this milestone</p>
                            ) : (
                              <div className="space-y-0.5">
                                {milestoneTasks.map((task) => (
                                  <button
                                    key={task.name}
                                    type="button"
                                    className="flex items-center gap-2 w-full py-1 text-left hover:bg-muted/50 px-1 -mx-1 rounded transition-colors"
                                    onClick={() => onTaskClick?.(task)}
                                  >
                                    <span className={`size-1.5 rounded-full shrink-0 ${TASK_STATUS_COLOR[task.status] ?? "bg-muted-foreground/40"}`} />
                                    <span className="text-xs truncate flex-1">{task.title}</span>
                                    {task.due_date && (
                                      <span className={`text-[10px] shrink-0 ${
                                        new Date(task.due_date) < new Date() && task.status !== "Done"
                                          ? "text-destructive"
                                          : "text-muted-foreground"
                                      }`}>
                                        {format(new Date(task.due_date), "MMM d")}
                                      </span>
                                    )}
                                  </button>
                                ))}
                              </div>
                            )}
                          </div>
                        </CollapsibleContent>
                      </Collapsible>
                    )
                  })}
              </div>
            ) : (
              <Empty>
                <EmptyHeader>
                  <EmptyMedia>
                    <HugeiconsIcon icon={Target02Icon} strokeWidth={1.5} className="size-8 text-muted-foreground" />
                  </EmptyMedia>
                  <EmptyTitle>No active milestones</EmptyTitle>
                  <EmptyDescription>Create milestones to track project progress.</EmptyDescription>
                </EmptyHeader>
              </Empty>
            )}
          </CardContent>
        </Card>

        {/* Team */}
        <Card>
          <CardHeader>
            <CardTitle className="text-sm font-medium flex items-center gap-2">
              <HugeiconsIcon icon={UserGroupIcon} strokeWidth={2} className="size-4" />
              Team
              {!isClient && (
                <Popover>
                  <PopoverTrigger
                    render={
                      <Button variant="ghost" size="icon-sm" className="ml-auto" />
                    }
                  >
                    <HugeiconsIcon icon={UserAdd01Icon} strokeWidth={2} className="size-4" />
                  </PopoverTrigger>
                  <PopoverContent className="w-64 p-2" align="end">
                    <div className="space-y-1 max-h-48 overflow-y-auto">
                      {allMembers?.length ? (
                        allMembers.map((m) => {
                          const isAssigned = teamMemberSet.has(m.name)
                          return (
                            <button
                              key={m.name}
                              type="button"
                              onClick={() => toggleTeamMember(m)}
                              className={`flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-sm hover:bg-muted transition-colors ${
                                isAssigned ? "bg-muted" : ""
                              }`}
                            >
                              <MemberAvatar size="sm" name={m.member_name || m.name} image={m.user_image} />
                              <span className="flex-1 truncate text-left">
                                {m.member_name || m.name}
                              </span>
                              {isAssigned && (
                                <HugeiconsIcon
                                  icon={CheckmarkCircle02Icon}
                                  strokeWidth={2}
                                  className="size-4 text-primary"
                                />
                              )}
                            </button>
                          )
                        })
                      ) : (
                        <p className="text-xs text-muted-foreground px-2 py-1">
                          No members found
                        </p>
                      )}
                    </div>
                  </PopoverContent>
                </Popover>
              )}
            </CardTitle>
          </CardHeader>
          <CardContent>
            {teamMembers.length ? (
              <div className="space-y-2">
                {teamMembers.map((m) => {
                  const memberData = allMembersByName.get(m.member)
                  return (
                    <div
                      key={m.member}
                      className="flex items-center gap-2 text-sm"
                    >
                      <MemberAvatar size="sm" name={m.member_name || m.member} image={memberData?.user_image} />
                      <span className="flex-1 truncate">
                        {m.member_name || m.member}
                      </span>
                      {isClient ? (
                        <Badge variant="outline" className="text-[10px] h-5 px-2">
                          {m.role}
                        </Badge>
                      ) : (
                        <>
                          <Select
                            value={m.role}
                            onValueChange={(role) =>
                              changeTeamMemberRole(m.member, role)
                            }
                          >
                            <SelectTrigger className="h-6 w-auto text-[10px] px-2 gap-1">
                              <SelectValue />
                            </SelectTrigger>
                            <SelectContent>
                              <SelectItem value="Member">Member</SelectItem>
                              <SelectItem value="Champion">Champion</SelectItem>
                              <SelectItem value="Stakeholder">
                                Stakeholder
                              </SelectItem>
                            </SelectContent>
                          </Select>
                          <button
                            type="button"
                            onClick={() => removeTeamMember(m.member)}
                            className="text-muted-foreground hover:text-destructive transition-colors"
                          >
                            <HugeiconsIcon
                              icon={Cancel02Icon}
                              strokeWidth={2}
                              className="size-3.5"
                            />
                          </button>
                        </>
                      )}
                    </div>
                  )
                })}
              </div>
            ) : (
              <Empty>
                <EmptyHeader>
                  <EmptyMedia>
                    <HugeiconsIcon icon={UserGroupIcon} strokeWidth={1.5} className="size-8 text-muted-foreground" />
                  </EmptyMedia>
                  <EmptyTitle>No team members</EmptyTitle>
                  <EmptyDescription>Add members using the button above.</EmptyDescription>
                </EmptyHeader>
              </Empty>
            )}
          </CardContent>
        </Card>
      </div>

    </div>
  )
}

function StatCard({
  label,
  value,
  variant,
}: {
  label: string
  value: number
  variant?: "destructive"
}) {
  return (
    <Card>
      <CardContent className="pt-4">
        <p className="text-xs text-muted-foreground">{label}</p>
        <p
          className={`text-2xl font-bold mt-1 ${
            variant === "destructive" ? "text-destructive" : ""
          }`}
        >
          {value}
        </p>
      </CardContent>
    </Card>
  )
}
